// <auto-generated />
using System;
using HR.Report.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.Report.Infrastructure.Migrations
{
    [DbContext(typeof(ReportContext))]
    [Migration("20251124161631_MicrossRffepivesds")]
    partial class MicrossRffepivesds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.BaseTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MetaData")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Base_Table", "bas");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.BaseTableValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseTableId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BaseTableId");

                    b.ToTable("Base_Table_Value", "bas");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.OrganizationType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Organization_Type", "bas");
                });

            modelBuilder.Entity("HR.Organisation.Core.Entities.OrganisationChart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCostCenter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsIndependentOrg")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOrg")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPayLocation")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRegister")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LetterCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("OrgTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizationTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentOrganisationChartId")
                        .HasColumnType("bigint");

                    b.Property<string>("Rank")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SystemCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("TaxNodeStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationTypeId");

                    b.HasIndex("ParentOrganisationChartId");

                    b.ToTable("Organisation_Chart", "Org");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.DynamicReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ExportTypeId")
                        .HasColumnType("bigint")
                        .HasComment("base table value Id : 40286 (excel or pdf)");

                    b.Property<long>("FuctionTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FunctionName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Help")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<long>("OrganisationChartId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganisationMRTId")
                        .HasColumnType("bigint");

                    b.Property<string>("Schema")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SqlQuery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ExportTypeId");

                    b.HasIndex("FuctionTypeId");

                    b.HasIndex("OrganisationChartId");

                    b.HasIndex("OrganisationMRTId");

                    b.ToTable("Dynamic_Report", "rpt");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.DynamicReportParameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("DynamicReportId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Optional")
                        .HasColumnType("bit");

                    b.Property<long>("ParameterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicReportId");

                    b.HasIndex("ParameterId");

                    b.ToTable("Dynamic_Report_Parameter", "rpt");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.EmployeeProperty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AccDay")
                        .HasColumnType("int");

                    b.Property<int?>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AccountTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ActiveName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AddressType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AddressTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApproveTimePaymentPeriod")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ApproverSignatureDate")
                        .HasColumnType("date");

                    b.Property<string>("ApproverSignatureGuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ArearsStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("AspNetUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AspNetUsersId")
                        .HasColumnType("bigint");

                    b.Property<string>("BankAccountDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BankBranchId")
                        .HasColumnType("int");

                    b.Property<long?>("BankId")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseOrganisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BaseOrganisationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("BasijDuration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BirthPlaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BloodGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("BonCardNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CaptivityDuration")
                        .HasColumnType("int");

                    b.Property<int?>("ChildCount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("CompeleteInsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfidentialityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ConfidentialityLevelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ConfirmedLetterDate")
                        .HasColumnType("date");

                    b.Property<string>("ConfirmedLetterNo")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ConfirmerOrganID")
                        .HasColumnType("bigint");

                    b.Property<bool?>("ContactInfoIsVerify")
                        .HasColumnType("bit");

                    b.Property<string>("CorrectedInterdictOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CorrectedInterdictOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CostCenterId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CostCenterPercent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Descriptions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("DrivingLicenseNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("DrivingLicenseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DueType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DueTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EducatioFieldId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EducatioOrientationId")
                        .HasColumnType("bigint");

                    b.Property<string>("EducationAverage")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("EducationDescriptions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EducationField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EducationFromDate")
                        .HasColumnType("date");

                    b.Property<string>("EducationGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EducationGradeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EducationLicenseExpireDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EducationLicenseImplDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EducationLicensePresentDate")
                        .HasColumnType("date");

                    b.Property<string>("EducationOrientation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationPlaces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EducationPlacesId")
                        .HasColumnType("bigint");

                    b.Property<string>("EducationState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EducationStateID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EducationToDate")
                        .HasColumnType("date");

                    b.Property<string>("EffectiveEducationGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EffectiveEducationGradeId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmergencyPhone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EmpEdu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EmpEduID")
                        .HasColumnType("bigint");

                    b.Property<string>("Employee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmployeeDate")
                        .HasColumnType("date");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EmployeeStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EmployeeTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ExperienceRecorded")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("ExpiresOn")
                        .HasColumnType("datetime");

                    b.Property<string>("FatherName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Fax")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("date");

                    b.Property<int?>("FromPrice")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GenderId")
                        .HasColumnType("bigint");

                    b.Property<int?>("GradScore")
                        .HasColumnType("int");

                    b.Property<bool?>("HasSupplementaryInsurance")
                        .HasColumnType("bit");

                    b.Property<string>("HeadquartersOrRowType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("HeadquartersOrRowTypeId")
                        .HasColumnType("bigint");

                    b.Property<int?>("HistoryOut")
                        .HasColumnType("int");

                    b.Property<int?>("HistoryStop")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IdentityNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ImmunityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ImmunityTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ImmunityValidDate")
                        .HasColumnType("date");

                    b.Property<int?>("Imperfective")
                        .HasColumnType("int");

                    b.Property<string>("InOutCard")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InsWorkShopType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InsWorkShopTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsuranceBranchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsuranceInsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("InsuranceIsLast")
                        .HasColumnType("bit");

                    b.Property<string>("InsuranceNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("InsuranceSubmissionCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InsuranceSubmissionCityId")
                        .HasColumnType("bigint");

                    b.Property<string>("InsuranceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsArrears")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBasij")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBoursie")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCaptivity")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCashBenefits")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsComputable")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsContinue")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDefaultEducation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHekmat")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsInDutyTime")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsIsar")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLast")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMartyrs")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRetired")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUsedInOrder")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVerify")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsWar")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsWelfareBenefits")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsWomenHead")
                        .HasColumnType("bit");

                    b.Property<float?>("IsarPercent")
                        .HasColumnType("real");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("IssuePlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IssuePlaceId")
                        .HasColumnType("bigint");

                    b.Property<int?>("IssueSerialChar")
                        .HasColumnType("int");

                    b.Property<string>("IssueSerialOrder")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IssueSerialString")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IssueType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IssueTypeId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("int");

                    b.Property<int?>("JobDegree")
                        .HasColumnType("int");

                    b.Property<long?>("KindOfGraduationId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastInterdictOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LastInterdictOrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastToken")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("LastWrongAttemptDatetime")
                        .HasColumnType("datetime");

                    b.Property<string>("LicenceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("LicenceTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LifeAccidentInsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("LocationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LocationTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("LostIssueSerialString")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mail")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ManagementAndStewardshipJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ManagementAndStewardshipJobId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<string>("MarriageStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MarriageStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("MartyrChildTrackingCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MartyrRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MartyrRelationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mazhab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MazhabId")
                        .HasColumnType("bigint");

                    b.Property<string>("MilitariGradeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MilitariGradeTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MilitariIssueDate")
                        .HasColumnType("date");

                    b.Property<string>("MilitariSerialNo")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MilitaryDuration")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("MilitaryEndDate")
                        .HasColumnType("date");

                    b.Property<string>("MilitaryFullDuration")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MilitaryMinDuration")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MilitaryServiceDescriptions")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("MilitaryServiceEducationGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MilitaryServiceEducationGradeId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("MilitaryServiceIsLast")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MilitaryStartDate")
                        .HasColumnType("date");

                    b.Property<string>("MilitaryStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MilitaryStatusCodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NameOfPeriod")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NationalNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NationalityId")
                        .HasColumnType("bigint");

                    b.Property<int?>("OldId")
                        .HasColumnType("int");

                    b.Property<string>("OrderReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("OrderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrderTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganisationChartId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrganisationPositionDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrganisationPositionDetailId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrganizationJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrganizationJobId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrganizationUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrganizationUnitId")
                        .HasColumnType("bigint");

                    b.Property<string>("OtherUniversityName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OtherVeterans")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PayLocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("PayRollApproveUser")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("PayRollAprove")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PayRollAproveDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("PayRollRealExecuteDate")
                        .HasColumnType("date");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("PersonelCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool?>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("PrivateJobStatus")
                        .HasColumnType("int");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("RecruitOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RecruitOrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Religeon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReligeonId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("RetiredFlagOk")
                        .HasColumnType("bit");

                    b.Property<string>("RetiredRecorded")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("SectId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Serial")
                        .HasColumnType("smallint");

                    b.Property<string>("ServicePlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ServicePlaceId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("SetByEmployee")
                        .HasColumnType("bit");

                    b.Property<string>("ShabaNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SkillLevelId")
                        .HasColumnType("bigint");

                    b.Property<short?>("SponsorshipCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartWorkDate")
                        .HasColumnType("date");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("SubsystemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SumWageFactors")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupplementaryInsuranceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SupplementaryInsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaminInsuranceJobList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TaminInsuranceJobListId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaxExemptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TaxExemptionTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ThesisGradeTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ThesisGradeValueId")
                        .HasColumnType("bigint");

                    b.Property<string>("ThesisTitle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("date");

                    b.Property<int?>("ToPrice")
                        .HasColumnType("int");

                    b.Property<bool?>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UniversityId")
                        .HasColumnType("bigint");

                    b.Property<string>("UniversityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UniversityLevelId")
                        .HasColumnType("bigint");

                    b.Property<string>("UniversityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UniversityTypeID")
                        .HasColumnType("bigint");

                    b.Property<long?>("UseCompeleteInsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UseLifeAccidentInsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ValidationCodeSendDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("VehicleStatusId")
                        .HasColumnType("bigint");

                    b.Property<int?>("WarDuration")
                        .HasColumnType("int");

                    b.Property<int?>("WifeCount")
                        .HasColumnType("int");

                    b.Property<string>("WorkPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("WorkPlaceId")
                        .HasColumnType("bigint");

                    b.Property<byte?>("YearCoefficient")
                        .HasColumnType("tinyint");

                    b.Property<string>("YearRecorded")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationChartId");

                    b.ToTable("Employee_Property", "rpt");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.FieldDataType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Field_DataType", "rpt");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.FieldOperator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<long>("FieldDataTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FieldDataTypeId");

                    b.ToTable("Field_Operator", "rpt");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.ReportableEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Schema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Reportable_Entity", "rpt");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.ReportableField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<long>("FieldDataTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelectable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NavigationPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<long>("ReportableEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TechnicalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FieldDataTypeId");

                    b.HasIndex("ReportableEntityId");

                    b.ToTable("Reportable_Field", "rpt");
                });

            modelBuilder.Entity("HR.SharedKernel.Data.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Hr.SystemSetting.Core.Entities.OrganisationMRT", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MimeType")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("OrganisationChartId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationChartId");

                    b.ToTable("Organisation_MRT", "Setting");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.BaseTableValue", b =>
                {
                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTable", "BaseTable")
                        .WithMany("BaseTableValues")
                        .HasForeignKey("BaseTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseTable");
                });

            modelBuilder.Entity("HR.Organisation.Core.Entities.OrganisationChart", b =>
                {
                    b.HasOne("HR.BaseInfo.Core.Entities.OrganizationType", "OrganizationType")
                        .WithMany()
                        .HasForeignKey("OrganizationTypeId");

                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "ParentOrganisationChart")
                        .WithMany()
                        .HasForeignKey("ParentOrganisationChartId");

                    b.Navigation("OrganizationType");

                    b.Navigation("ParentOrganisationChart");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.DynamicReport", b =>
                {
                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "ExportType")
                        .WithMany()
                        .HasForeignKey("ExportTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "FuctionType")
                        .WithMany()
                        .HasForeignKey("FuctionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "OrganisationChart")
                        .WithMany()
                        .HasForeignKey("OrganisationChartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hr.SystemSetting.Core.Entities.OrganisationMRT", "OrganisationMRT")
                        .WithMany()
                        .HasForeignKey("OrganisationMRTId");

                    b.Navigation("ExportType");

                    b.Navigation("FuctionType");

                    b.Navigation("OrganisationChart");

                    b.Navigation("OrganisationMRT");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.DynamicReportParameter", b =>
                {
                    b.HasOne("HR.Report.Core.Entity.DynamicReport", "DynamicReport")
                        .WithMany()
                        .HasForeignKey("DynamicReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DynamicReport");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.EmployeeProperty", b =>
                {
                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "OrganisationChart")
                        .WithMany()
                        .HasForeignKey("OrganisationChartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganisationChart");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.FieldOperator", b =>
                {
                    b.HasOne("HR.Report.Core.Entity.FieldDataType", "FieldDataType")
                        .WithMany("FieldOperators")
                        .HasForeignKey("FieldDataTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldDataType");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.ReportableField", b =>
                {
                    b.HasOne("HR.Report.Core.Entity.FieldDataType", "FieldDataType")
                        .WithMany("ReportableFields")
                        .HasForeignKey("FieldDataTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Report.Core.Entity.ReportableEntity", "ReportableEntity")
                        .WithMany("Fields")
                        .HasForeignKey("ReportableEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldDataType");

                    b.Navigation("ReportableEntity");
                });

            modelBuilder.Entity("Hr.SystemSetting.Core.Entities.OrganisationMRT", b =>
                {
                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "OrganisationChart")
                        .WithMany()
                        .HasForeignKey("OrganisationChartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganisationChart");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.BaseTable", b =>
                {
                    b.Navigation("BaseTableValues");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.FieldDataType", b =>
                {
                    b.Navigation("FieldOperators");

                    b.Navigation("ReportableFields");
                });

            modelBuilder.Entity("HR.Report.Core.Entity.ReportableEntity", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
