using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HR.Report.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class MicrossRffepivesds : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Employee_Property",
                schema: "rpt",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    OrganisationChartId = table.Column<long>(type: "bigint", nullable: false),
                    GenderId = table.Column<long>(type: "bigint", nullable: true),
                    Gender = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ReligeonId = table.Column<long>(type: "bigint", nullable: true),
                    Religeon = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MazhabId = table.Column<long>(type: "bigint", nullable: true),
                    Mazhab = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NationalityId = table.Column<long>(type: "bigint", nullable: true),
                    Nationality = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ServicePlaceId = table.Column<long>(type: "bigint", nullable: true),
                    ServicePlace = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BloodGroupId = table.Column<long>(type: "bigint", nullable: true),
                    BloodGroup = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActiveName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    Descriptions = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    PersonId = table.Column<long>(type: "bigint", nullable: true),
                    PrivateJobStatus = table.Column<int>(type: "int", nullable: true),
                    IssueDate = table.Column<DateTime>(type: "date", nullable: true),
                    ValidationCodeSendDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IssueSerialChar = table.Column<int>(type: "int", nullable: true),
                    IssueSerialString = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    IssueSerialOrder = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    MaritalStatusId = table.Column<int>(type: "int", nullable: true),
                    PassportNo = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    InOutCard = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    SectId = table.Column<int>(type: "int", nullable: true),
                    IsActive = table.Column<bool>(type: "bit", nullable: true),
                    IsVerify = table.Column<bool>(type: "bit", nullable: true),
                    BaseOrganisationId = table.Column<long>(type: "bigint", nullable: true),
                    BaseOrganisation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SkillLevelId = table.Column<long>(type: "bigint", nullable: true),
                    SkillLevel = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsRetired = table.Column<bool>(type: "bit", nullable: true),
                    SubsystemId = table.Column<int>(type: "int", nullable: true),
                    Imperfective = table.Column<int>(type: "int", nullable: true),
                    StartWorkDate = table.Column<DateTime>(type: "date", nullable: true),
                    LostIssueSerialString = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    UseLifeAccidentInsuranceTypeId = table.Column<long>(type: "bigint", nullable: true),
                    LifeAccidentInsuranceTypeId = table.Column<long>(type: "bigint", nullable: true),
                    UseCompeleteInsuranceTypeId = table.Column<long>(type: "bigint", nullable: true),
                    CompeleteInsuranceTypeId = table.Column<long>(type: "bigint", nullable: true),
                    IsHekmat = table.Column<bool>(type: "bit", nullable: true),
                    IsCashBenefits = table.Column<bool>(type: "bit", nullable: true),
                    IsWelfareBenefits = table.Column<bool>(type: "bit", nullable: true),
                    ReleaseReason = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    ReleaseDate = table.Column<DateTime>(type: "date", nullable: true),
                    VehicleStatusId = table.Column<long>(type: "bigint", nullable: true),
                    EmailConfirmed = table.Column<bool>(type: "bit", nullable: true),
                    Disabled = table.Column<bool>(type: "bit", nullable: true),
                    PasswordHash = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SecurityStamp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TwoFactorEnabled = table.Column<bool>(type: "bit", nullable: true),
                    IsAdmin = table.Column<bool>(type: "bit", nullable: true),
                    PhoneNumber = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                    PhoneNumberConfirmed = table.Column<bool>(type: "bit", nullable: true),
                    AccessFailedCount = table.Column<int>(type: "int", nullable: true),
                    Salt = table.Column<byte[]>(type: "varbinary(max)", nullable: true),
                    LastLoginDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    LastWrongAttemptDatetime = table.Column<DateTime>(type: "datetime", nullable: true),
                    ExpiresOn = table.Column<DateTime>(type: "datetime", nullable: true),
                    LastToken = table.Column<string>(type: "nvarchar(1024)", maxLength: 1024, nullable: true),
                    TaxExemptionTypeId = table.Column<long>(type: "bigint", nullable: true),
                    TaxExemptionType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ManagementAndStewardshipJobId = table.Column<long>(type: "bigint", nullable: true),
                    ManagementAndStewardshipJob = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HeadquartersOrRowTypeId = table.Column<long>(type: "bigint", nullable: true),
                    HeadquartersOrRowType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MartyrRelationId = table.Column<long>(type: "bigint", nullable: true),
                    MartyrRelation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MartyrChildTrackingCode = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    TaminInsuranceJobListId = table.Column<long>(type: "bigint", nullable: true),
                    TaminInsuranceJobList = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConfidentialityLevelId = table.Column<long>(type: "bigint", nullable: true),
                    ConfidentialityLevel = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EducationStateID = table.Column<long>(type: "bigint", nullable: true),
                    EducationState = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UniversityLevelId = table.Column<long>(type: "bigint", nullable: true),
                    UniversityLevel = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UniversityTypeID = table.Column<long>(type: "bigint", nullable: true),
                    UniversityType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EducationFromDate = table.Column<DateTime>(type: "date", nullable: true),
                    EducationToDate = table.Column<DateTime>(type: "date", nullable: true),
                    EducationAverage = table.Column<string>(type: "nvarchar(8)", maxLength: 8, nullable: true),
                    EducationLicensePresentDate = table.Column<DateTime>(type: "date", nullable: true),
                    EducationLicenseImplDate = table.Column<DateTime>(type: "date", nullable: true),
                    EducationLicenseExpireDate = table.Column<DateTime>(type: "date", nullable: true),
                    IsInDutyTime = table.Column<bool>(type: "bit", nullable: true),
                    EducationPlacesId = table.Column<long>(type: "bigint", nullable: true),
                    EducationPlaces = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EducationDescriptions = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    IsBoursie = table.Column<bool>(type: "bit", nullable: true),
                    ThesisTitle = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    UniversityId = table.Column<long>(type: "bigint", nullable: true),
                    University = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsDefaultEducation = table.Column<bool>(type: "bit", nullable: true),
                    IsUsedInOrder = table.Column<bool>(type: "bit", nullable: true),
                    SetByEmployee = table.Column<bool>(type: "bit", nullable: true),
                    LicenceTypeId = table.Column<long>(type: "bigint", nullable: true),
                    LicenceNumber = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    OtherUniversityName = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    KindOfGraduationId = table.Column<long>(type: "bigint", nullable: true),
                    ThesisGradeTypeId = table.Column<long>(type: "bigint", nullable: true),
                    ThesisGradeValueId = table.Column<long>(type: "bigint", nullable: true),
                    BankAccountNumber = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    AccountTypeId = table.Column<long>(type: "bigint", nullable: true),
                    AccountType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Priority = table.Column<int>(type: "int", nullable: true),
                    FromPrice = table.Column<int>(type: "int", nullable: true),
                    ToPrice = table.Column<int>(type: "int", nullable: true),
                    Status = table.Column<bool>(type: "bit", nullable: true),
                    BankAccountDescription = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: true),
                    BankId = table.Column<long>(type: "bigint", nullable: true),
                    BankBranchId = table.Column<int>(type: "int", nullable: true),
                    OldId = table.Column<int>(type: "int", nullable: true),
                    BonCardNumber = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    ShabaNumber = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    AddressTypeId = table.Column<long>(type: "bigint", nullable: true),
                    AddressType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Address = table.Column<string>(type: "nvarchar(300)", maxLength: 300, nullable: true),
                    Zipcode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    Phone = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: true),
                    EmergencyPhone = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: true),
                    Fax = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: true),
                    Mail = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    LocationTypeId = table.Column<long>(type: "bigint", nullable: true),
                    LocationType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MobileNo = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                    ContactInfoIsVerify = table.Column<bool>(type: "bit", nullable: true),
                    IsLast = table.Column<bool>(type: "bit", nullable: true),
                    InsWorkShopTypeId = table.Column<long>(type: "bigint", nullable: true),
                    InsWorkShopType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InsuranceBranchId = table.Column<long>(type: "bigint", nullable: true),
                    InsuranceInsuranceTypeId = table.Column<long>(type: "bigint", nullable: true),
                    AccDay = table.Column<int>(type: "int", nullable: true),
                    InsuranceIsLast = table.Column<bool>(type: "bit", nullable: true),
                    InsuranceNumber = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: true),
                    HasSupplementaryInsurance = table.Column<bool>(type: "bit", nullable: true),
                    SupplementaryInsuranceTypeId = table.Column<long>(type: "bigint", nullable: true),
                    SupplementaryInsuranceType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InsuranceSubmissionCityId = table.Column<long>(type: "bigint", nullable: true),
                    InsuranceSubmissionCity = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MilitaryStatusCodeId = table.Column<long>(type: "bigint", nullable: true),
                    MilitaryStatusCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ImmunityTypeId = table.Column<long>(type: "bigint", nullable: true),
                    ImmunityType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConfirmerOrganID = table.Column<long>(type: "bigint", nullable: true),
                    NameOfPeriod = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    MilitaryDuration = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    MilitaryFullDuration = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    MilitaryMinDuration = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    ConfirmedLetterDate = table.Column<DateTime>(type: "date", nullable: true),
                    ConfirmedLetterNo = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    MilitaryStartDate = table.Column<DateTime>(type: "date", nullable: true),
                    MilitaryEndDate = table.Column<DateTime>(type: "date", nullable: true),
                    MilitariIssueDate = table.Column<DateTime>(type: "date", nullable: true),
                    ImmunityValidDate = table.Column<DateTime>(type: "date", nullable: true),
                    MilitariGradeTypeId = table.Column<long>(type: "bigint", nullable: true),
                    MilitariGradeType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MilitariSerialNo = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    MilitaryServiceDescriptions = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: true),
                    IsContinue = table.Column<bool>(type: "bit", nullable: true),
                    MilitaryServiceIsLast = table.Column<bool>(type: "bit", nullable: true),
                    DueTypeId = table.Column<long>(type: "bigint", nullable: true),
                    DueType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MilitaryServiceEducationGradeId = table.Column<long>(type: "bigint", nullable: true),
                    MilitaryServiceEducationGrade = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsComputable = table.Column<bool>(type: "bit", nullable: true),
                    FromDate = table.Column<DateTime>(type: "date", nullable: true),
                    ToDate = table.Column<DateTime>(type: "date", nullable: true),
                    RecruitOrderId = table.Column<long>(type: "bigint", nullable: true),
                    RecruitOrder = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UniqueId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    Code = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SumWageFactors = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Serial = table.Column<short>(type: "smallint", nullable: true),
                    CreatorUserName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    OrderTypeId = table.Column<long>(type: "bigint", nullable: true),
                    OrderType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IssueTypeId = table.Column<long>(type: "bigint", nullable: true),
                    IssueType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MarriageStatusId = table.Column<long>(type: "bigint", nullable: true),
                    MarriageStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InsuranceTypeId = table.Column<long>(type: "bigint", nullable: true),
                    InsuranceType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AspNetUsersId = table.Column<long>(type: "bigint", nullable: true),
                    AspNetUsers = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Description = table.Column<string>(type: "nvarchar(2048)", maxLength: 2048, nullable: true),
                    LastInterdictOrderId = table.Column<long>(type: "bigint", nullable: true),
                    LastInterdictOrder = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CorrectedInterdictOrderId = table.Column<long>(type: "bigint", nullable: true),
                    CorrectedInterdictOrder = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EducatioFieldId = table.Column<long>(type: "bigint", nullable: true),
                    EducationField = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EducatioOrientationId = table.Column<long>(type: "bigint", nullable: true),
                    EducationOrientation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BirthDate = table.Column<DateTime>(type: "date", nullable: true),
                    EmpEduID = table.Column<long>(type: "bigint", nullable: true),
                    EmpEdu = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BirthPlaceId = table.Column<long>(type: "bigint", nullable: true),
                    BirthPlace = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DrivingLicenseNumber = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                    IssuePlaceId = table.Column<long>(type: "bigint", nullable: true),
                    IssuePlace = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ExperienceRecorded = table.Column<string>(type: "nvarchar(8)", maxLength: 8, nullable: true),
                    RetiredRecorded = table.Column<string>(type: "nvarchar(8)", maxLength: 8, nullable: true),
                    YearRecorded = table.Column<string>(type: "nvarchar(8)", maxLength: 8, nullable: true),
                    HistoryOut = table.Column<int>(type: "int", nullable: true),
                    HistoryStop = table.Column<int>(type: "int", nullable: true),
                    RetiredFlagOk = table.Column<bool>(type: "bit", nullable: true),
                    SponsorshipCount = table.Column<short>(type: "smallint", nullable: true),
                    YearCoefficient = table.Column<byte>(type: "tinyint", nullable: true),
                    EducationGradeId = table.Column<long>(type: "bigint", nullable: true),
                    EducationGrade = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EffectiveEducationGradeId = table.Column<long>(type: "bigint", nullable: true),
                    EffectiveEducationGrade = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsWar = table.Column<bool>(type: "bit", nullable: true),
                    IsCaptivity = table.Column<bool>(type: "bit", nullable: true),
                    IsBasij = table.Column<bool>(type: "bit", nullable: true),
                    IsIsar = table.Column<bool>(type: "bit", nullable: true),
                    IsarPercent = table.Column<float>(type: "real", nullable: true),
                    WarDuration = table.Column<int>(type: "int", nullable: true),
                    CaptivityDuration = table.Column<int>(type: "int", nullable: true),
                    BasijDuration = table.Column<int>(type: "int", nullable: true),
                    JobDegree = table.Column<int>(type: "int", nullable: true),
                    IsMartyrs = table.Column<bool>(type: "bit", nullable: true),
                    WifeCount = table.Column<int>(type: "int", nullable: true),
                    GradScore = table.Column<int>(type: "int", nullable: true),
                    EmployeeDate = table.Column<DateTime>(type: "date", nullable: true),
                    ApproverSignatureGuid = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AccountNumber = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    OtherVeterans = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    ApproverSignatureDate = table.Column<DateTime>(type: "date", nullable: true),
                    IsWomenHead = table.Column<bool>(type: "bit", nullable: true),
                    FirstName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    LastName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    FatherName = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: true),
                    PersonelCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    IdentityNo = table.Column<string>(type: "nvarchar(15)", maxLength: 15, nullable: true),
                    NationalNo = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    OrderReason = table.Column<string>(type: "nvarchar(2048)", maxLength: 2048, nullable: true),
                    DrivingLicenseTypeId = table.Column<int>(type: "int", nullable: true),
                    ChildCount = table.Column<int>(type: "int", nullable: true),
                    PayRollAprove = table.Column<bool>(type: "bit", nullable: true),
                    PayRollAproveDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    PayRollRealExecuteDate = table.Column<DateTime>(type: "date", nullable: true),
                    ItemCount = table.Column<int>(type: "int", nullable: true),
                    ArearsStatusId = table.Column<long>(type: "bigint", nullable: true),
                    IsArrears = table.Column<bool>(type: "bit", nullable: true),
                    ApproveTimePaymentPeriod = table.Column<long>(type: "bigint", nullable: true),
                    PayRollApproveUser = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    EmployeeId = table.Column<long>(type: "bigint", nullable: true),
                    Employee = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PayLocationId = table.Column<long>(type: "bigint", nullable: true),
                    PayLocation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CostCenterId = table.Column<long>(type: "bigint", nullable: true),
                    CostCenter = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CostCenterPercent = table.Column<int>(type: "int", nullable: true),
                    OrganizationUnitId = table.Column<long>(type: "bigint", nullable: true),
                    OrganizationUnit = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WorkPlaceId = table.Column<long>(type: "bigint", nullable: true),
                    WorkPlace = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProjectId = table.Column<long>(type: "bigint", nullable: true),
                    Project = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EmployeeStatusId = table.Column<long>(type: "bigint", nullable: true),
                    EmployeeStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EmployeeTypeId = table.Column<long>(type: "bigint", nullable: true),
                    EmployeeType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrganizationJobId = table.Column<long>(type: "bigint", nullable: true),
                    OrganizationJob = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrganisationPositionDetailId = table.Column<long>(type: "bigint", nullable: true),
                    OrganisationPositionDetail = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    title = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    CreateDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    LastModifiedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    IPAddress = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    StartDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    EndDate = table.Column<DateTime>(type: "datetime", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Employee_Property", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Employee_Property_Organisation_Chart_OrganisationChartId",
                        column: x => x.OrganisationChartId,
                        principalSchema: "Org",
                        principalTable: "Organisation_Chart",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Employee_Property_OrganisationChartId",
                schema: "rpt",
                table: "Employee_Property",
                column: "OrganisationChartId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Employee_Property",
                schema: "rpt");
        }
    }
}
