namespace HR.SharedKernel.Extensions;

public static class PermissionKeyDescription
{
    public static Dictionary<string, string> CustomAccessKeyDesc = new()
    {
  
        // Employee
        {"Employee.Ability.create", "ایجاد Ability"},
        {"Employee.Ability.delete", "حذف Ability"},
        {"Employee.Ability.update", "بروزرسانی Ability"},
        {"Employee.Ability.view", "مشاهده Ability"},
        {"Employee.Appearance.create", "ایجاد وضعیت ظاهری"},
        {"Employee.Appearance.delete", "حذف وضعیت ظاهری"},
        {"Employee.Appearance.update", "بروزرسانی وضعیت ظاهری"},
        {"Employee.Appearance.view", "مشاهده وضعیت ظاهری"},
        {"Employee.Attendance.create", "ایجاد تردد"},
        {"Employee.Attendance.delete", "حذف تردد"},
        {"Employee.Attendance.update", "بروزرسانی تردد"},
        {"Employee.Attendance.view", "مشاهده تردد"},
        {"Attendance.AbsenceType.create", "ایجاد نوع عدم حضور"},
        {"Attendance.AbsenceType.delete", "حذف نوع عدم حضور"},
        {"Attendance.AbsenceType.update", "بروزرسانی نوع عدم حضور"},
        {"Attendance.AbsenceType.view", "مشاهده نوع عدم حضور"},
        {"Attendance.AttendanceLocation.create", "ایجاد محل حضور"},
        {"Attendance.AttendanceLocation.delete", "حذف محل حضور"},
        {"Attendance.AttendanceLocation.update", "بروزرسانی محل حضور"},
        {"Attendance.AttendanceLocation.view", "مشاهده محل حضور"},
        {"Attendance.AttendanceDevice.create", "ایجاد دستگاه حضور"},
        {"Attendance.AttendanceDevice.delete", "حذف دستگاه حضور"},
        {"Attendance.AttendanceDevice.update", "بروزرسانی دستگاه حضور"},
        {"Attendance.AttendanceDevice.view", "مشاهده دستگاه حضور"},
        {"Attendance.AttendanceCalendar.create", "ایجاد تقویم حضور و غیاب"},
        {"Attendance.AttendanceCalendar.delete", "حذف تقویم حضور و غیاب"},
        {"Attendance.AttendanceCalendar.update", "بروزرسانی تقویم حضور و غیاب"},
        {"Attendance.AttendanceCalendar.view", "مشاهده تقویم حضور و غیاب"},
        {"Attendance.AttendanceLog.create", "ایجاد لاگ تردد"},
        {"Attendance.AttendanceLog.delete", "حذف لاگ تردد"},
        {"Attendance.AttendanceLog.update", "بروزرسانی لاگ تردد"},
        {"Attendance.AttendanceLog.view", "مشاهده لاگ تردد"},
        {"Attendance.Shift.create", "ایجاد شیفت"},
        {"Attendance.Shift.delete", "حذف شیفت"},
        {"Attendance.Shift.update", "بروزرسانی شیفت"},
        {"Attendance.Shift.view", "مشاهده شیفت"},
        {"Attendance.ShiftOverride.create", "ایجاد بازتعریف شیفت"},
        {"Attendance.ShiftOverride.delete", "حذف بازتعریف شیفت"},
        {"Attendance.ShiftOverride.update", "بروزرسانی بازتعریف شیفت"},
        {"Attendance.ShiftOverride.view", "مشاهده بازتعریف شیفت"},
        {"Attendance.EmployeeShiftAssignment.create", "ایجاد تخصیص شیفت کارمند"},
        {"Attendance.EmployeeShiftAssignment.delete", "حذف تخصیص شیفت کارمند"},
        {"Attendance.EmployeeShiftAssignment.update", "بروزرسانی تخصیص شیفت کارمند"},
        {"Attendance.EmployeeShiftAssignment.view", "مشاهده تخصیص شیفت کارمند"},
        {"Attendance.EmployeeMonthlySummary.create", "ایجاد خلاصه ماهانه حضور کارمند"},
        {"Attendance.EmployeeMonthlySummary.delete", "حذف خلاصه ماهانه حضور کارمند"},
        {"Attendance.EmployeeMonthlySummary.update", "بروزرسانی خلاصه ماهانه حضور کارمند"},
        {"Attendance.EmployeeMonthlySummary.view", "مشاهده خلاصه ماهانه حضور کارمند"},
        {"Attendance.EmployeeAttendanceDailyResult.create", "ایجاد نتیجه روزانه حضور کارمند"},
        {"Attendance.EmployeeAttendanceDailyResult.delete", "حذف نتیجه روزانه حضور کارمند"},
        {"Attendance.EmployeeAttendanceDailyResult.update", "بروزرسانی نتیجه روزانه حضور کارمند"},
        {"Attendance.EmployeeAttendanceDailyResult.view", "مشاهده نتیجه روزانه حضور کارمند"},
        {"Attendance.EmployeeAttendanceException.create", "ایجاد استثناء عدم حضور کارمند"},
        {"Attendance.EmployeeAttendanceException.delete", "حذف استثناء عدم حضور کارمند"},
        {"Attendance.EmployeeAttendanceException.update", "بروزرسانی استثناء عدم حضور کارمند"},
        {"Attendance.EmployeeAttendanceException.view", "مشاهده استثناء عدم حضور کارمند"},
        {"Attendance.EmployeeExceptionJustificationRequestState.create", "ایجاد وضعیت درخواست توجیه استثناء کارمند"},
        {"Attendance.EmployeeExceptionJustificationRequestState.delete", "حذف وضعیت درخواست توجیه استثناء کارمند"},
        {"Attendance.EmployeeExceptionJustificationRequestState.update", "بروزرسانی وضعیت درخواست توجیه استثناء کارمند"},
        {"Attendance.EmployeeExceptionJustificationRequestState.view", "مشاهده وضعیت درخواست توجیه استثناء کارمند"},
        {"Attendance.EmployeeExceptionJustificationRequest.create", "ایجاد درخواست توجیه استثناء کارمند"},
        {"Attendance.EmployeeExceptionJustificationRequest.delete", "حذف درخواست توجیه استثناء کارمند"},
        {"Attendance.EmployeeExceptionJustificationRequest.update", "بروزرسانی درخواست توجیه استثناء کارمند"},
        {"Attendance.EmployeeExceptionJustificationRequest.view", "مشاهده درخواست توجیه استثناء کارمند"},
        {"Attendance.EmployeeHome.view", "مشاهده حضور و غیاب کارمند"},
        {"Employee.BankAccount.create", "ایجاد حساب بانکی"},
        {"Employee.BankAccount.delete", "حذف حساب بانکی"},
        {"Employee.BankAccount.update", "بروزرسانی حساب بانکی"},
        {"Employee.BankAccount.view", "مشاهده حساب بانکی"},
        {"Employee.Basij.create", "ایجاد بسیج"},
        {"Employee.Basij.delete", "حذف بسیج"},
        {"Employee.Basij.update", "بروزرسانی بسیج"},
        {"Employee.Basij.view", "مشاهده بسیج"},
        {"Employee.BasijGrade.create", "ایجاد درجه بسیج"},
        {"Employee.BasijGrade.delete", "حذف درجه بسیج"},
        {"Employee.BasijGrade.update", "بروزرسانی درجه بسیج"},
        {"Employee.BasijGrade.view", "مشاهده درجه بسیج"},

        {"Employee.Experience.create", "ایجاد سابقه"},
        {"Employee.Experience.delete", "حذف سابقه"},
        {"Employee.Experience.update", "بروزرسانی سابقه"},
        {"Employee.Experience.view", "مشاهده سابقه"},

        {"Employee.Captivity.create", "ایجاد اسارت"},
        {"Employee.Captivity.delete", "حذف اسارت"},
        {"Employee.Captivity.update", "بروزرسانی اسارت"},
        {"Employee.Captivity.view", "مشاهده اسارت"},

        {"Employee.Character.create", "ایجاد Character"},
        {"Employee.Character.delete", "حذف Character"},
        {"Employee.Character.update", "بروزرسانی Character"},
        {"Employee.Character.view", "مشاهده Character"},
        {"Employee.Competency.create", "ایجاد شایستگی"},
        {"Employee.Competency.delete", "حذف شایستگی"},
        {"Employee.Competency.update", "بروزرسانی شایستگی"},
        {"Employee.Competency.view", "مشاهده شایستگی"},
        {"Employee.ContactInfo.create", "ایجاد اطلاعات تماس"},
        {"Employee.ContactInfo.delete", "حذف اطلاعات تماس"},
        {"Employee.ContactInfo.update", "بروزرسانی اطلاعات تماس"},
        {"Employee.ContactInfo.view", "مشاهده اطلاعات تماس"},
        {"Employee.Course.create", "ایجاد دوره ها"},
        {"Employee.Course.delete", "حذف دوره ها"},
        {"Employee.Course.update", "بروزرسانی دوره ها"},
        {"Employee.Course.view", "مشاهده دوره ها"},
        {"Employee.Disability.create", "ایجاد معلولیت"},
        {"Employee.Disability.delete", "حذف معلولیت"},
        {"Employee.Disability.update", "بروزرسانی معلولیت"},
        {"Employee.Disability.view", "مشاهده معلولیت"},
        {"Employee.DrivingLicense.create", "ایجاد گواهینامه رانندگی"},
        {"Employee.DrivingLicense.delete", "حذف گواهینامه رانندگی"},
        {"Employee.DrivingLicense.update", "بروزرسانی گواهینامه رانندگی"},
        {"Employee.DrivingLicense.view", "مشاهده گواهینامه رانندگی"},
        {"Employee.Education.create", "ایجاد تحصیلات"},
        {"Employee.Education.delete", "حذف تحصیلات"},
        {"Employee.Education.update", "بروزرسانی تحصیلات"},
        {"Employee.Education.view", "مشاهده تحصیلات"},
        {"Employee.Employee.create", "ایجاد کارکنان"},
        {"Employee.Employee.delete", "حذف کارکنان"},
        {"Employee.Employee.update", "بروزرسانی کارکنان"},
        {"Employee.Employee.view", "مشاهده کارکنان"},
        {"Employee.Employee.AdvanceSearch", "جستجو کارکنان"},
        {"Employee.Employee.Summary", "خلاصه اطلاعات کارمند"},
        {"Employee.Employee.GetMyUnfinishedEmployeesCount", "تعداد کارکنان بدون حکم نهایی (دسترسی کاربر)"},
        {"Employee.EmployeeFile.create", "ایجاد مستندات کارمند"},
        {"Employee.EmployeeFile.delete", "حذف مستندات کارمند"},
        {"Employee.EmployeeFile.update", "بروزرسانی مستندات کارمند"},
        {"Employee.EmployeeFile.view", "مشاهده مستندات کارمند"},
        {"Employee.EmployeeRequest.create", "ایجاد درخواست کارمند"},
        {"Employee.EmployeeRequest.delete", "حذف درخواست کارمند"},
        {"Employee.EmployeeRequest.update", "بروزرسانی درخواست کارمند"},
        {"Employee.EmployeeRequest.view", "مشاهده کارتابل درخواست‌های کارکنان"},
        {"Employee.EmployeeSoftware.create", "ایجاد نرم افزار های کارمند"},
        {"Employee.EmployeeSoftware.delete", "حذف نرم افزار های کارمند"},
        {"Employee.EmployeeSoftware.update", "بروزرسانی نرم افزار های کارمند"},
        {"Employee.EmployeeSoftware.view", "مشاهده نرم افزار های کارمند"},
        {"Employee.EvaluationResult.create", "ایجاد نتایج ارزشیابی"},
        {"Employee.EvaluationResult.delete", "حذف نتایج ارزشیابی"},
        {"Employee.EvaluationResult.update", "بروزرسانی نتایج ارزشیابی"},
        {"Employee.EvaluationResult.view", "مشاهده نتایج ارزشیابی"},
        {"Employee.Family.create", "ایجاد بستگان"},
        {"Employee.Family.delete", "حذف بستگان"},
        {"Employee.Family.update", "بروزرسانی بستگان"},
        {"Employee.Family.view", "مشاهده بستگان"},
        {"Employee.ForeignTravel.create", "ایجاد سفر های خارجی"},
        {"Employee.ForeignTravel.delete", "حذف سفر های خارجی"},
        {"Employee.ForeignTravel.update", "بروزرسانی سفر های خارجی"},
        {"Employee.ForeignTravel.view", "مشاهده سفر های خارجی"},
        {"Employee.ForeignLanguage.create", "ایجاد زبان های خارجی"},
        {"Employee.ForeignLanguage.delete", "حذف زبان های خارجی"},
        {"Employee.ForeignLanguage.update", "بروزرسانی زبان های خارجی"},
        {"Employee.ForeignLanguage.view", "مشاهده زبان های خارجی"},
        {"Employee.GroupPunishmentEncourage.create", "ایجاد تنبیه و تشویق گروهی"},
        {"Employee.GroupPunishmentEncourage.delete", "حذف تنبیه و تشویق گروهی"},
        {"Employee.GroupPunishmentEncourage.update", "بروزرسانی تنبیه و تشویق گروهی"},
        {"Employee.GroupPunishmentEncourage.view", "مشاهده تنبیه و تشویق گروهی"},
        {"Employee.HistoryStop.create", "ایجاد قطع خدمتی"},
        {"Employee.HistoryStop.delete", "حذف قطع خدمتی"},
        {"Employee.HistoryStop.update", "بروزرسانی قطع خدمتی"},
        {"Employee.HistoryStop.view", "مشاهده قطع خدمتی"},
        {"Employee.Image.create", "ایجاد تصویر کاربر"},
        {"Employee.Image.delete", "حذف تصویر کاربر"},
        {"Employee.Image.update", "بروزرسانی تصویر کاربر"},
        {"Employee.Image.view", "مشاهده تصویر کاربر"},
        {"Employee.Insurance.create", "ایجاد بیمه"},
        {"Employee.Insurance.delete", "حذف بیمه"},
        {"Employee.Insurance.update", "بروزرسانی بیمه"},
        {"Employee.Insurance.view", "مشاهده بیمه"},
        {"Employee.InsuranceDetail.create", "ایجاد جزئیات بیمه"},
        {"Employee.InsuranceDetail.delete", "حذف جزئیات بیمه"},
        {"Employee.InsuranceDetail.update", "بروزرسانی جزئیات بیمه"},
        {"Employee.InsuranceDetail.view", "مشاهده جزئیات بیمه"},
        {"Employee.Isar.create", "ایجاد ایثارگری"},
        {"Employee.Isar.delete", "حذف ایثارگری"},
        {"Employee.Isar.update", "بروزرسانی ایثارگری"},
        {"Employee.Isar.view", "مشاهده ایثارگری"},
        {"Employee.MilitaryService.create", "ایجاد خدمت سربازی"},
        {"Employee.MilitaryService.delete", "حذف خدمت سربازی"},
        {"Employee.MilitaryService.update", "بروزرسانی خدمت سربازی"},
        {"Employee.MilitaryService.view", "مشاهده خدمت سربازی"},
        {"Employee.OtherVeteran.create", "ایجاد سایر ایثارگری"},
        {"Employee.OtherVeteran.delete", "حذف سایر ایثارگری"},
        {"Employee.OtherVeteran.update", "بروزرسانی سایر ایثارگری"},
        {"Employee.OtherVeteran.view", "مشاهده سایر ایثارگری"},
        {"Employee.PunishmentEncourage.create", "ایجاد PunishmentEncourage"},
        {"Employee.PunishmentEncourage.delete", "حذف PunishmentEncourage"},
        {"Employee.PunishmentEncourage.update", "بروزرسانی PunishmentEncourage"},
        {"Employee.PunishmentEncourage.view", "مشاهده PunishmentEncourage"},
        {"Employee.War.create", "ایجاد War"},
        {"Employee.War.delete", "حذف War"},
        {"Employee.War.update", "بروزرسانی War"},
        {"Employee.War.view", "مشاهده War"},

        // FormulaEngine
        {"FormulaEngine.FormulaDatabaseFunctionDefinition.create", "ایجاد تعریف تابع پایگاه داده ها"},
        {"FormulaEngine.FormulaDatabaseFunctionDefinition.delete", "حذف تعریف تابع پایگاه داده ها"},
        {"FormulaEngine.FormulaDatabaseFunctionDefinition.update", "بروزرسانی تعریف تابع پایگاه داده ها"},
        {"FormulaEngine.FormulaDatabaseFunctionDefinition.view", "مشاهده تعریف تابع پایگاه داده ها"},
        {"FormulaEngine.FormulaDefinition.create", "ایجاد تعریف فرمول ها"},
        {"FormulaEngine.FormulaDefinition.delete", "حذف تعریف فرمول ها"},
        {"FormulaEngine.FormulaDefinition.update", "بروزرسانی تعریف فرمول ها"},
        {"FormulaEngine.FormulaDefinition.view", "مشاهده تعریف فرمول ها"},
        {"FormulaEngine.FormulaDefinition.GetHistory", "مشاهده تاریخچه تغییرات فرمول"},
        {"FormulaEngine.FormulaDefinition.GetFormulaCountsByOrganisation", "مشاهده آمار تعداد فرمول‌ها به تفکیک سازمان"},
        {"FormulaEngine.FormulaOperand.create", "ایجاد FormulaOperand"},
        {"FormulaEngine.FormulaOperand.delete", "حذف FormulaOperand"},
        {"FormulaEngine.FormulaOperand.update", "بروزرسانی FormulaOperand"},
        {"FormulaEngine.FormulaOperand.view", "مشاهده FormulaOperand"},
        {"FormulaEngine.FormulaTable.create", "ایجاد جدول فرمول ها"},
        {"FormulaEngine.FormulaTable.delete", "حذف جدول فرمول ها"},
        {"FormulaEngine.FormulaTable.update", "بروزرسانی جدول فرمول ها"},
        {"FormulaEngine.FormulaTable.view", "مشاهده جدول فرمول ها"},
        {"FormulaEngine.FormulaTableValue.create", "ایجاد جدول پایه فرمول"},
        {"FormulaEngine.FormulaTableValue.delete", "حذف جدول پایه فرمول"},
        {"FormulaEngine.FormulaTableValue.update", "بروزرسانی جدول پایه فرمول"},
        {"FormulaEngine.FormulaTableValue.view", "مشاهده جدول پایه فرمول"},

        // IdentityManager
        {"IdentityManager.AspNetRoles.create", "ایجاد نقش کاربران"},
        {"IdentityManager.AspNetRoles.delete", "حذف نقش کاربران"},
        {"IdentityManager.AspNetRoles.update", "بروزرسانی نقش کاربران"},
        {"IdentityManager.AspNetRoles.view", "مشاهده نقش کاربران"},
        {"IdentityManager.AspNetUsers.create", "ایجاد کاربران"},
        {"IdentityManager.AspNetUsers.delete", "حذف کاربران"},
        {"IdentityManager.AspNetUsers.update", "بروزرسانی کاربران"},
        {"IdentityManager.AspNetUsers.getCurrentUserLastLoginDate", "مشاهده زمان آخرین لاگین کاربر جاری"},

        {"IdentityManager.AspNetUsers.view", "مشاهده کاربران"},
        {"IdentityManager.AspNetUsers.UpdateCurrentUserPassword", "تغییر رمز عبور کاربر جاری"},
        {"IdentityManager.AspNetUsers.GetCurrentUserBasicInfo", "مشاهده اطلاعات کاربر جاری"},
        {"IdentityManager.AspNetUsers.Unlock", "بازکردن قفل کاربر"},
        {"IdentityManager.Identity.create", "ایجاد احراز هویت"},
        {"IdentityManager.Identity.GetcurrentUserEmployeeId", "GetcurrentUserEmployeeId"},
        {"IdentityManager.Identity.GetCurrentUserId", "GetCurrentUserId"},
        {"IdentityManager.Identity.delete", "حذف احراز هویت"},
        {"IdentityManager.Identity.Logout", "خروج از سامانه"},
        {"IdentityManager.Identity.update", "بروزرسانی احراز هویت"},
        {"IdentityManager.Identity.view", "مشاهده احراز هویت"},
        {"IdentityManager.Identity.GetCurrentUserName", "مشاهده اطلاعات کاربر جاری"},
        {"IdentityManager.Identity.public-key", "دریافت کلید عمومی ورود"},
        {"IdentityManager.PermissionRoute.create", "ایجاد مسیر منو"},
        {"IdentityManager.PermissionRoute.delete", "حذف مسیر منو"},
        {"IdentityManager.PermissionRoute.update", "بروز رسانی مسیر منو"},
        {"IdentityManager.PermissionRoute.view", "مشاهده مسیر منو"},
        {"IdentityManager.PermissionRoute.GetCurrentUserMenu", "مشاهده منو کاربرجاری"},
        {"IdentityManager.PermissionRoute.GetRouteAccessContext", "دریافت نقشه دسترسی مسیرها"},
        {"IdentityManager.Permissions.GetAll", "مشاهده همه"},
        {"IdentityManager.Permissions.GetAllForSelectedRole", "مشاهده همه دسترسی ها برای یک نقش خاص"},
        {"IdentityManager.Permissions.GetAllForSelectedUser", "مشاهده همه دسترسی ها برای یک کاربر خاص"},
        {"IdentityManager.UserDefaultSetting.Admin.create", "ایجاد تنظیمات پیش فرض کاربر (ادمین)"},
        {"IdentityManager.UserDefaultSetting.Admin.delete", "حذف تنظیمات پیش فرض کاربر (ادمین)"},
        {"IdentityManager.UserDefaultSetting.Admin.update", "بروزرسانی تنظیمات پیش فرض کاربر (ادمین)"},
        {"IdentityManager.UserDefaultSetting.Admin.view", "مشاهده تنظیمات پیش فرض کاربر (ادمین)"},
        {"IdentityManager.UserDefaultSetting.CurrentUser.update", "بروزرسانی تنظیمات پیش فرض کاربر جاری"},
        {"IdentityManager.UserDefaultSetting.CurrentUser.view", "مشاهده تنظیمات پیش فرض کاربر جاری"},
        {"IdentityManager.Permissions.Initialize", "اسکن دسترسی ها"},
        {"IdentityManager.RoleMenu.GetAllForSelectedUser", "مشاهده دسترسی منو برای منو"},
        {"IdentityManager.RoleMenu.Post", "اعطا دسترسی منو به نقش"},
        {"IdentityManager.RoleMenu.RevokeAccess", "گرفتن دسترسی منو از نقش"},
        {"IdentityManager.RoleReportableEntity.create", "ایجاد موجودیت قابل گزارش نقش"},
        {"IdentityManager.RoleReportableEntity.delete", "حذف موجودیت قابل گزارش نقش"},
        {"IdentityManager.RoleReportableEntity.update", "بروزرسانی موجودیت قابل گزارش نقش"},
        {"IdentityManager.RoleReportableEntity.view", "مشاهده موجودیت قابل گزارش نقش"},
        {"IdentityManager.UserReportableEntity.create", "ایجاد موجودیت قابل گزارش کاربر"},
        {"IdentityManager.UserReportableEntity.delete", "حذف موجودیت قابل گزارش کاربر"},
        {"IdentityManager.UserReportableEntity.update", "بروزرسانی موجودیت قابل گزارش کاربر"},
        {"IdentityManager.UserReportableEntity.view", "مشاهده موجودیت قابل گزارش کاربر"},
        {"IdentityManager.UserCostCenter.create", "ایجاد مرکز هزینه کاربر"},
        {"IdentityManager.UserCostCenter.delete", "حذف مرکز هزینه کاربر"},
        {"IdentityManager.UserCostCenter.update", "بروزرسانی مرکز هزینه کاربر"},
        {"IdentityManager.UserCostCenter.view", "مشاهده مرکز هزینه کاربر"},

        {"IdentityManager.UserLoginHistory.create", "ایجاد تاریخچه ورود کاربر"},
        {"IdentityManager.UserLoginHistory.delete", "حذف تاریخچه ورود کاربر"},
        {"IdentityManager.UserLoginHistory.update", "بروزرسانی تاریخچه ورود کاربر"},
        {"IdentityManager.UserLoginHistory.view", "مشاهده تاریخچه ورود کاربر"},
        {"IdentityManager.UserMenu.GetAllForSelectedUser", "مشاهده دسترسی منو برای کاربر"},
        {"IdentityManager.UserMenu.Post", "اعطا دسترسی منو به کاربر"},
        {"IdentityManager.UserMenu.RevokeAccess", "گرفتن دسترسی منو از کاربر"},
        {"IdentityManager.UserOrganizationUnit.create", "ایجاد واحد سازمانی کاربر"},
        {"IdentityManager.UserOrganizationUnit.delete", "حذف واحد سازمانی کاربر"},
        {"IdentityManager.UserOrganizationUnit.update", "بروزرسانی واحد سازمانی کاربر"},
        {"IdentityManager.UserOrganizationUnit.view", "مشاهده واحد سازمانی کاربر"},
        {"IdentityManager.UserPayLocation.create", "ایجاد محل پرداخت های کاربر"},
        {"IdentityManager.UserPayLocation.delete", "حذف محل پرداخت های کاربر"},
        {"IdentityManager.UserPayLocation.update", "بروزرسانی محل پرداخت های کاربر"},
        {"IdentityManager.UserPayLocation.view", "مشاهده محل پرداخت های کاربر"},
        {"IdentityManager.UserReport.create", "ایجاد گزارش کاربر"},
        {"IdentityManager.UserReport.delete", "حذف گزارش کاربر"},
        {"IdentityManager.UserReport.update", "بروزرسانی گزارش کاربر"},
        {"IdentityManager.UserReport.view", "مشاهده گزارش کاربر"},
        {"IdentityManager.UserReport.GetCurrentUserAvailableReports", "مشاهده فهرست دسترسی های گزارش کاربر جاری"},
        {"IdentityManager.RoleReport.create", "ایجاد گزارش نقش"},
        {"IdentityManager.RoleReport.delete", "حذف گزارش نقش"},
        {"IdentityManager.RoleReport.update", "بروزرسانی گزارش نقش"},
        {"IdentityManager.RoleReport.view", "مشاهده گزارش نقش"},
        {"IdentityManager.RoleReport.GetCurrentRoleAvailableReports", "مشاهده فهرست دسترسی های گزارش نقش جاری"},
        {"IdentityManager.UserWorkPlace.create", "ایجاد محل خدمت کاربر"},
        {"IdentityManager.UserWorkPlace.delete", "حذف محل خدمت کاربر"},
        {"IdentityManager.UserWorkPlace.update", "بروزرسانی محل خدمت کاربر"},
        {"IdentityManager.UserWorkPlace.view", "مشاهده محل خدمت کاربر"},

        {"IdentityManager.CommonPassword.create", "ایجاد کلمه عبور متداول"},
        {"IdentityManager.CommonPassword.delete", "حذف کلمه عبور متداول"},
        {"IdentityManager.CommonPassword.update", "بروزرسانی کلمه عبور متداول"},
        {"IdentityManager.CommonPassword.view", "مشاهده کلمه عبور متداول"},
        {"IdentityManager.BlockedIp.create", "ایجاد آدرس IP مسدود شده"},
        {"IdentityManager.BlockedIp.delete", "حذف آدرس IP مسدود شده"},
        {"IdentityManager.BlockedIp.update", "بروزرسانی آدرس IP مسدود شده"},
        {"IdentityManager.BlockedIp.view", "مشاهده آدرس IP مسدود شده"},

        {"IdentityManager.RoleAccess.create", "ایجاد دسترسی برای نقش"},
        {"IdentityManager.RoleAccess.RevokeAccess", "گرفتن دسترسی نقش"},

        {"IdentityManager.UserAccess.create", "ایجاد دسترسی برای کاربر"},
        {"IdentityManager.UserAccess.RevokeAccess", "گرفتن دسترسی کاربر"},

        {"IdentityManager.UserRole.view", "مشاهده نقش کاربران"},
        {"IdentityManager.UserRole.create", "درج نقش کاربران"},
        {"IdentityManager.UserRole.delete", "حذف نقش کاربران"},

        {"IdentityManager.Message.GetInbox", "مشاهده صندوق ورودی پیام‌ها"},
        {"IdentityManager.Message.GetMessageWithThread", "مشاهده پیام با thread"},
        {"IdentityManager.Message.SendMessage", "ارسال پیام"},
        {"IdentityManager.Message.DownloadAttachment", "دانلود پیوست پیام"},
        {"IdentityManager.Message.GetActiveUsers", "مشاهده فهرست کاربران فعال"},
        {"IdentityManager.Message.GetUnreadMessageCount", "مشاهده تعداد پیام‌های خوانده نشده"},
        {"IdentityManager.Message.MarkAsRead", "علامت‌گذاری پیام به عنوان خوانده شده"},
        {"IdentityManager.Message.GetAllMessages", "مشاهده تمام پیام‌ها"},
        {"IdentityManager.Message.SendMessageToAllUsers", "ارسال پیام به همه کاربران"},
        {"IdentityManager.Message.DownloadAttachmentFile", "دانلود فایل پیوست"},
    
        // Order
        {"OrderNameSpace.BatchRequest.create", "ایجاد BatchRequest"},
        {"OrderNameSpace.BatchRequest.delete", "حذف BatchRequest"},
        {"OrderNameSpace.BatchRequest.update", "بروزرسانی BatchRequest"},
        {"OrderNameSpace.BatchRequest.view", "مشاهده BatchRequest"},
        {"OrderNameSpace.BatchRequestDetail.create", "ایجاد جزئیات درخواست گروهی"},
        {"OrderNameSpace.BatchRequestDetail.delete", "حذف جزئیات درخواست گروهی"},
        {"OrderNameSpace.BatchRequestDetail.update", "بروزرسانی جزئیات درخواست گروهی"},
        {"OrderNameSpace.BatchRequestDetail.view", "مشاهده جزئیات درخواست گروهی"},
        {"OrderNameSpace.Order.GetLastOrderDetailByEmployeeId", "مشاهده آخرین حکم کاربر"},
        {"OrderNameSpace.Order.GetOrderLandingPageSummary", "مشاهده خلاصه حکم صفحه اول"},
        {"OrderNameSpace.Order.GetOrderYearlyLandingPageSummary", "مشاهده خلاصه سالانه احکام صادره کاربر جاری"},
        {"OrderNameSpace.Order.GetInterdictCountsByStatus", "مشاهده آمار احکام به تفکیک وضعیت"},
        {"OrderNameSpace.Order.GetInterdictCountsByPayLocation", "مشاهده آمار احکام به تفکیک محل پرداخت"},
        {"OrderNameSpace.Order.PrintPdf", "دانلود PDF حکم"},
        {"OrderNameSpace.Order.GetInterdictOrderArchiveStatus", "مشاهده وضعیت آرشیو PDF حکم"},
        {"OrderNameSpace.Order.DownloadInterdictOrderArchivePdf", "دانلود PDF آرشیو حکم"},
        {"OrderNameSpace.Order.RebuildInterdictOrderArchive", "ایجاد یا بروزرسانی آرشیو PDF حکم"},
        {"OrderNameSpace.Order.GetOrderForPrint", "دریافت حکم برای چاپ"},
        {"OrderNameSpace.Order.SendOrderToCartable", "ارسال حکم به کارتابل"},
        {"OrderNameSpace.Order.UpdateDraftOrderDates", "ویرایش تاریخ حکم پیش‌نویس"},
        {"OrderNameSpace.Order.GetSelectedOrderLastOrderForCorrectAndCancellation", "دریافت آخرین حکم برای تصحیح/ابطال"},
        {"OrderNameSpace.Order.GetOrderFlat", "دریافت حکم به صورت فلت"},
        {"OrderNameSpace.Order.GetAllPendingOrders", "مشاهده احکام در انتظار"},
        {"OrderNameSpace.Order.FinalApproveOrder", "تایید نهایی حکم"},
        {"OrderNameSpace.Order.FinalApproveOrderAll", "تایید نهایی همه احکام"},
        {"OrderNameSpace.Order.RejectOrderSingle", "رد یک حکم"},
        {"OrderNameSpace.Order.RejectOrderAll", "رد همه احکام"},
        {"OrderNameSpace.Order.GetExpiringOrdersList", "کارتابل رهایی"},
        {"OrderNameSpace.Order.GetSettlementCartableList", "کارتابل تسویه حساب"},
        {"OrderNameSpace.Order.GetCurrentMonthFirstDay", "دریافت اولین روز ماه جاری"},
        {"OrderNameSpace.Order.GetOrderCartableDetail", "مشاهده جزئیات کارتابل حکم"},
        {"OrderNameSpace.Order.create", "صدور حکم"},
        {"OrderNameSpace.Order.delete", "حذف حکم پیش نویس یا رد شده"},
        {"OrderNameSpace.Order.CompareInterdictOrders", "مقایسه با حکم قبلی"},
        {"OrderNameSpace.Order.GetMyIssuedOrdersList", "مشاهده فهرست احکام صادره من"},
        {"OrderNameSpace.OrderAdmin.create", "ایجاد ادمین احکام"},
        {"OrderNameSpace.OrderAdmin.delete", "حذف ادمین احکام"},
        {"OrderNameSpace.OrderAdmin.update", "بروزرسانی ادمین احکام"},
        {"OrderNameSpace.OrderAdmin.view", "مشاهده ادمین احکام"},

        // Organisation
        {"Organisation.Abundance.create", "ایجاد پیچیدگی"},
        {"Organisation.Abundance.delete", "حذف پیچیدگی"},
        {"Organisation.Abundance.update", "بروزرسانی پیچیدگی"},
        {"Organisation.Abundance.view", "مشاهده پیچیدگی"},
        {"Organisation.Complexity.create", "ایجاد پیچیدگی"},
        {"Organisation.Complexity.delete", "حذف پیچیدگی"},
        {"Organisation.Complexity.update", "بروزرسانی پیچیدگی"},
        {"Organisation.Complexity.view", "مشاهده پیچیدگی"},
        
        // PayRoll - EmployeeDeduction
        {"PayRoll.EmployeeDeduction.create", "ایجاد کسور کارکنان"},
        {"PayRoll.EmployeeDeduction.delete", "حذف کسور کارکنان"},
        {"PayRoll.EmployeeDeduction.update", "بروزرسانی کسور کارکنان"},
        {"PayRoll.EmployeeDeduction.view", "مشاهده کسور کارکنان"},
        {"PayRoll.EmployeeSettlement.create", "ایجاد تسویه حساب کارکنان"},
        {"PayRoll.EmployeeSettlement.delete", "حذف تسویه حساب کارکنان"},
        {"PayRoll.EmployeeSettlement.update", "بروزرسانی تسویه حساب کارکنان"},
        {"PayRoll.EmployeeSettlement.view", "مشاهده تسویه حساب کارکنان"},
        {"PayRoll.EmployeeSettlement.CalculateSettlement", "محاسبه تسویه حساب کارکنان"},
        {"PayRoll.EmployeeSettlement.PrintPdf", "دانلود PDF تسویه حساب"},
        {"PayRoll.EmployeeSettlement.GetEmployeeSettlementArchiveStatus", "مشاهده وضعیت آرشیو PDF تسویه حساب"},
        {"PayRoll.EmployeeSettlement.DownloadEmployeeSettlementArchivePdf", "دانلود PDF آرشیو تسویه حساب"},
        {"PayRoll.EmployeeSettlement.RebuildEmployeeSettlementArchive", "ایجاد یا بروزرسانی آرشیو PDF تسویه حساب"},
        {"PayRoll.EmployeeSettlement.SendSettlementToCartable", "ارسال تسویه حساب به کارتابل تاییدکننده"},
        {"PayRoll.EmployeeSettlement.GetSettlementCartableDetail", "مشاهده جزئیات گردش کار تسویه حساب"},
        {"PayRoll.EmployeeSettlement.GetOrganisationSettlementCartableList", "مشاهده کارتابل سازمانی تسویه حساب"},
        {"PayRoll.EmployeeSettlementAttachment.create", "ایجاد پیوست سند تسویه حساب"},
        {"PayRoll.EmployeeSettlementAttachment.delete", "حذف پیوست سند تسویه حساب"},
        {"PayRoll.EmployeeSettlementAttachment.update", "بروزرسانی پیوست سند تسویه حساب"},
        {"PayRoll.EmployeeSettlementAttachment.view", "مشاهده پیوست سند تسویه حساب"},
        {"PayRoll.EmployeeSettlementAttachment.Download", "دانلود پیوست سند تسویه حساب"},
        // PayRoll - EmployeeDeductionUpload (آپلود گروهی کسورات)
        {"PayRoll.EmployeeDeductionUpload.create", "آپلود گروهی کسورات"},
        {"PayRoll.EmployeeDeductionUpload.delete", "حذف دسته آپلود کسورات"},
        {"PayRoll.EmployeeDeductionUpload.view", "مشاهده پیش‌نمایش و گزارش آپلود کسورات"},
        {"PayRoll.EmployeeFund.create", "ایجاد صندوق کارمند"},
        {"PayRoll.EmployeeFund.delete", "حذف صندوق کارمند"},
        {"PayRoll.EmployeeFund.update", "بروزرسانی صندوق کارمند"},
        {"PayRoll.EmployeeFund.view", "مشاهده صندوق کارمند"},
        {"PayRoll.OrganisationLeave.create", "ایجاد مرخصی سازمان"},
        {"PayRoll.OrganisationLeave.delete", "حذف مرخصی سازمان"},
        {"PayRoll.OrganisationLeave.update", "بروزرسانی مرخصی سازمان"},
        {"PayRoll.OrganisationLeave.view", "مشاهده مرخصی سازمان"},
        {"PayRoll.OrganisationFundTypeDefinition.create", "ایجاد تعریف نوع صندوق سازمان"},
        {"PayRoll.OrganisationFundTypeDefinition.delete", "حذف تعریف نوع صندوق سازمان"},
        {"PayRoll.OrganisationFundTypeDefinition.update", "بروزرسانی تعریف نوع صندوق سازمان"},
        {"PayRoll.OrganisationFundTypeDefinition.view", "مشاهده تعریف نوع صندوق سازمان"},
        {"PayRoll.OrganisationEmployeeTypeLeave.create", "ایجاد مرخصی نوع استخدام سازمان"},
        {"PayRoll.OrganisationEmployeeTypeLeave.delete", "حذف مرخصی نوع استخدام سازمان"},
        {"PayRoll.OrganisationEmployeeTypeLeave.update", "بروزرسانی مرخصی نوع استخدام سازمان"},
        {"PayRoll.OrganisationEmployeeTypeLeave.view", "مشاهده مرخصی نوع استخدام سازمان"},
        {"PayRoll.EmployeeLeaveEntitlement.create", "ایجاد سهمیه مرخصی سالانه"},
        {"PayRoll.EmployeeLeaveEntitlement.delete", "حذف سهمیه مرخصی سالانه"},
        {"PayRoll.EmployeeLeaveEntitlement.update", "بروزرسانی سهمیه مرخصی سالانه"},
        {"PayRoll.EmployeeLeaveEntitlement.view", "مشاهده سهمیه مرخصی سالانه"},
        {"PayRoll.PersonnelLeave.create", "ایجاد مرخصی کارکنان"},
        {"PayRoll.PersonnelLeave.delete", "حذف مرخصی کارکنان"},
        {"PayRoll.PersonnelLeave.update", "بروزرسانی مرخصی کارکنان"},
        {"PayRoll.PersonnelLeave.view", "مشاهده مرخصی کارکنان"},
        {"Organisation.G20ScoreDomainJobDegree.create", "ایجاد G20ScoreDomainJobDegree"},
        {"Organisation.G20ScoreDomainJobDegree.delete", "حذف G20ScoreDomainJobDegree"},
        {"Organisation.G20ScoreDomainJobDegree.update", "بروزرسانی G20ScoreDomainJobDegree"},
        {"Organisation.G20ScoreDomainJobDegree.view", "مشاهده G20ScoreDomainJobDegree"},
        {"Organisation.JobAbundanceJobScoringFactorQuestion.create", "ایجاد JobAbundanceJobScoringFactorQuestion"},
        {"Organisation.JobAbundanceJobScoringFactorQuestion.delete", "حذف JobAbundanceJobScoringFactorQuestion"},
        {"Organisation.JobAbundanceJobScoringFactorQuestion.update", "بروزرسانی JobAbundanceJobScoringFactorQuestion"},
        {"Organisation.JobAbundanceJobScoringFactorQuestion.view", "مشاهده JobAbundanceJobScoringFactorQuestion"},
        {"Organisation.JobComplexityJobScoringFactorQuestion.create", "ایجاد JobComplexityJobScoringFactorQuestion"},
        {"Organisation.JobComplexityJobScoringFactorQuestion.delete", "حذف JobComplexityJobScoringFactorQuestion"},
        {"Organisation.JobComplexityJobScoringFactorQuestion.update", "بروزرسانی JobComplexityJobScoringFactorQuestion"},
        {"Organisation.JobComplexityJobScoringFactorQuestion.view", "مشاهده JobComplexityJobScoringFactorQuestion"},

        // Log Controller - Audit Logs
       // {"baseInfo.Log.view", "مشاهده لاگ سیستم"},
        {"baseInfo.Log.auditView", "مشاهده لاگ‌های حسابرسی"},
        {"baseInfo.Log.auditDetails", "مشاهده جزئیات لاگ حسابرسی"},
        {"Organisation.JobScoreAbundanceComplexity.create", "ایجاد پیچیدگیامتیاز شغل"},
        {"Organisation.JobScoreAbundanceComplexity.delete", "حذف پیچیدگیامتیاز شغل"},
        {"Organisation.JobScoreAbundanceComplexity.update", "بروزرسانی پیچیدگیامتیاز شغل"},
        {"Organisation.JobScoreAbundanceComplexity.view", "مشاهده پیچیدگیامتیاز شغل"},
        {"Organisation.JobScoringFactor.create", "ایجاد فاکتور طبقه بندی مشاغل"},
        {"Organisation.JobScoringFactor.delete", "حذف فاکتور طبقه بندی مشاغل"},
        {"Organisation.JobScoringFactor.update", "بروزرسانی فاکتور طبقه بندی مشاغل"},
        {"Organisation.JobScoringFactor.view", "مشاهده فاکتور طبقه بندی مشاغل"},
        {"Organisation.OrganisationChart.create", "ایجاد چارت سازمانی"},
        {"Organisation.OrganisationChart.GetAllPayLocationsAsKeyValuePair", "مشاهده فهرست محل پرداخت ها"},
        {"Organisation.OrganisationChart.GetcurrentUserDefaultOrganId", "واکشی محل پرداخت پیش فرض کاربر جاری"},
        {"Organisation.OrganisationChart.delete", "حذف چارت سازمانی"},
        {"Organisation.OrganisationChart.update", "بروزرسانی چارت سازمانی"},
        {"Organisation.OrganisationChart.view", "مشاهده چارت سازمانی"},
        {"Organisation.OrganisationChart.GetAsTree", "مشاهده چارت درخت سازمانی"},
        {"Organisation.OrganisationChart.GetAsTreeFromCurrentUserDefaultOrgan", "مشاهده چارت بر اساس سطح دسترسی کاربر جاری"},
        {"Organisation.OrganisationChartImage.create", "ایجاد عکس چارت سازمانی"},
        {"Organisation.OrganisationChartImage.delete", "حذف عکس چارت سازمانی"},
        {"Organisation.OrganisationChartImage.update", "بروزرسانی عکس چارت سازمانی"},
        {"Organisation.OrganisationChartImage.view", "مشاهده عکس چارت سازمانی"},

        {"Organisation.OrganisationJobCategory.create", "ایجاد OrganisationJobCategory"},
        {"Organisation.OrganisationJobCategory.delete", "حذف OrganisationJobCategory"},
        {"Organisation.OrganisationJobCategory.update", "بروزرسانی OrganisationJobCategory"},
        {"Organisation.OrganisationJobCategory.view", "مشاهده OrganisationJobCategory"},
        {"Organisation.OrganisationJobGroup.create", "ایجاد OrganisationJobGroup"},
        {"Organisation.OrganisationJobGroup.delete", "حذف OrganisationJobGroup"},
        {"Organisation.OrganisationJobGroup.update", "بروزرسانی OrganisationJobGroup"},
        {"Organisation.OrganisationJobGroup.view", "مشاهده OrganisationJobGroup"},
        {"Organisation.OrganisationJobSeries.create", "ایجاد OrganisationJobSeries"},
        {"Organisation.OrganisationJobSeries.delete", "حذف OrganisationJobSeries"},
        {"Organisation.OrganisationJobSeries.update", "بروزرسانی OrganisationJobSeries"},
        {"Organisation.OrganisationJobSeries.view", "مشاهده OrganisationJobSeries"},
        {"Organisation.OrganisationPosition.create", "ایجاد پست های سازمان"},
        {"Organisation.OrganisationPosition.delete", "حذف پست های سازمان"},
        {"Organisation.OrganisationPosition.update", "بروزرسانی پست های سازمان"},
        {"Organisation.OrganisationPosition.view", "مشاهده پست های سازمان"},
        {"Organisation.OrganisationPositionJob.create", "ایجاد مشاغل پست ها"},
        {"Organisation.OrganisationPositionJob.delete", "حذف مشاغل پست ها"},
        {"Organisation.OrganisationPositionJob.update", "بروزرسانی مشاغل پست ها"},
        {"Organisation.OrganisationPositionJob.view", "مشاهده مشاغل پست ها"},
        {"Organisation.OrganisationPositionSupervisor.create", "ایجاد OrganisationPositionSupervisor"},
        {"Organisation.OrganisationPositionSupervisor.delete", "حذف OrganisationPositionSupervisor"},
        {"Organisation.OrganisationPositionSupervisor.update", "بروزرسانی OrganisationPositionSupervisor"},
        {"Organisation.OrganisationPositionSupervisor.view", "مشاهده OrganisationPositionSupervisor"},
        {"Organisation.OrganisationProject.create", "ایجاد پروژه های سازمان"},
        {"Organisation.OrganisationProject.delete", "حذف پروژه های سازمان"},
        {"Organisation.OrganisationProject.update", "بروزرسانی پروژه های سازمان"},
        {"Organisation.OrganisationProject.view", "مشاهده پروژه های سازمان"},
        {"Organisation.OrganizationGoal.create", "ایجاد OrganizationGoal"},
        {"Organisation.OrganizationGoal.delete", "حذف OrganizationGoal"},
        {"Organisation.OrganizationGoal.update", "بروزرسانی OrganizationGoal"},
        {"Organisation.OrganizationGoal.view", "مشاهده OrganizationGoal"},
        {"Organisation.OrganizationJob.create", "ایجاد مشاغل سازمان"},
        {"Organisation.OrganizationJob.delete", "حذف مشاغل سازمان"},
        {"Organisation.OrganizationJob.update", "بروزرسانی مشاغل سازمان"},
        {"Organisation.OrganizationJob.view", "مشاهده مشاغل سازمان"},
        {"Organisation.OrganizationJobAbilityQualification.create", "ایجاد توانایی صلاحیت شرایط احراز شغل"},
        {"Organisation.OrganizationJobAbilityQualification.delete", "حذف توانایی صلاحیت شرایط احراز شغل"},
        {"Organisation.OrganizationJobAbilityQualification.update", "بروزرسانی توانایی صلاحیت شرایط احراز شغل"},
        {"Organisation.OrganizationJobAbilityQualification.view", "مشاهده توانایی صلاحیت شرایط احراز شغل"},
        {"Organisation.OrganizationJobCompetencyQualification.create", "ایجاد صلاحیت شایستگی شغلی سازمان"},
        {"Organisation.OrganizationJobCompetencyQualification.delete", "حذف صلاحیت شایستگی شغلی سازمان"},
        {"Organisation.OrganizationJobCompetencyQualification.update", "بروزرسانی صلاحیت شایستگی شغلی سازمان"},
        {"Organisation.OrganizationJobCompetencyQualification.view", "مشاهده صلاحیت شایستگی شغلی سازمان"},
        {"Organisation.OrganizationJobEducationFieldQualification.create", "ایجاد OrganizationJobEducationFieldQualification"},
        {"Organisation.OrganizationJobEducationFieldQualification.delete", "حذف OrganizationJobEducationFieldQualification"},
        {"Organisation.OrganizationJobEducationFieldQualification.update", "بروزرسانی OrganizationJobEducationFieldQualification"},
        {"Organisation.OrganizationJobEducationFieldQualification.view", "مشاهده OrganizationJobEducationFieldQualification"},
        {"Organisation.OrganizationJobEducationGradeQualification.create", "ایجاد شرایط احراز شغل - مقطع تحصیلی"},
        {"Organisation.OrganizationJobEducationGradeQualification.delete", "حذف شرایط احراز شغل - مقطع تحصیلی"},
        {"Organisation.OrganizationJobEducationGradeQualification.update", "بروزرسانی شرایط احراز شغل - مقطع تحصیلی"},
        {"Organisation.OrganizationJobEducationGradeQualification.view", "مشاهده شرایط احراز شغل - مقطع تحصیلی"},
        {"Organisation.OrganizationJobForeignLanguageQualification.create", "ایجاد شرایط احراز شغل زبان های خارجی"},
        {"Organisation.OrganizationJobForeignLanguageQualification.delete", "حذف شرایط احراز شغل زبان های خارجی"},
        {"Organisation.OrganizationJobForeignLanguageQualification.update", "بروزرسانی شرایط احراز شغل زبان های خارجی"},
        {"Organisation.OrganizationJobForeignLanguageQualification.view", "مشاهده شرایط احراز شغل زبان های خارجی"},
        {"Organisation.OrganizationJobInitialCourseQualification.create", "ایجاد دوره های اولیه شرایط احراز"},
        {"Organisation.OrganizationJobInitialCourseQualification.delete", "حذف دوره های اولیه شرایط احراز"},
        {"Organisation.OrganizationJobInitialCourseQualification.update", "بروزرسانی دوره های اولیه شرایط احراز"},
        {"Organisation.OrganizationJobInitialCourseQualification.view", "مشاهده دوره های اولیه شرایط احراز"},
        {"Organisation.OrganizationJobPerformanceEvaluationCriteriaDescription.create", "ایجاد شرح معیارهای ارزیابی عملکرد سازمان"},
        {"Organisation.OrganizationJobPerformanceEvaluationCriteriaDescription.delete", "حذف شرح معیارهای ارزیابی عملکرد سازمان"},
        {"Organisation.OrganizationJobPerformanceEvaluationCriteriaDescription.update", "بروزرسانی شرح معیارهای ارزیابی عملکرد سازمان"},
        {"Organisation.OrganizationJobPerformanceEvaluationCriteriaDescription.view", "مشاهده شرح معیارهای ارزیابی عملکرد سازمان"},
        {"Organisation.OrganizationJobPeriodicTaskDescription.create", "ایجاد وظایف دوره ای"},
        {"Organisation.OrganizationJobPeriodicTaskDescription.delete", "حذف وظایف دوره ای"},
        {"Organisation.OrganizationJobPeriodicTaskDescription.update", "بروزرسانی وظایف دوره ای"},
        {"Organisation.OrganizationJobPeriodicTaskDescription.view", "مشاهده وظایف دوره ای"},
        {"Organisation.OrganizationJobRequiredCharacterQualification.create", "ایجاد شخصیت مورد نیاز"},
        {"Organisation.OrganizationJobRequiredCharacterQualification.delete", "حذف شخصیت مورد نیاز"},
        {"Organisation.OrganizationJobRequiredCharacterQualification.update", "بروزرسانی شخصیت مورد نیاز"},
        {"Organisation.OrganizationJobRequiredCharacterQualification.view", "مشاهده شخصیت مورد نیاز"},
        {"Organisation.OrganizationJobRequiredSoftwaresQualification.create", "ایجاد شرایط احراز نرم افزار های مورد نیاز"},
        {"Organisation.OrganizationJobRequiredSoftwaresQualification.delete", "حذف شرایط احراز نرم افزار های مورد نیاز"},
        {"Organisation.OrganizationJobRequiredSoftwaresQualification.update", "بروزرسانی شرایط احراز نرم افزار های مورد نیاز"},
        {"Organisation.OrganizationJobRequiredSoftwaresQualification.view", "مشاهده شرایط احراز نرم افزار های مورد نیاز"},
        {"Organisation.OrganizationJobRiskAndFaultDescription.create", "ایجاد شرح سازمان کار خطر و خطا"},
        {"Organisation.OrganizationJobRiskAndFaultDescription.delete", "حذف شرح سازمان کار خطر و خطا"},
        {"Organisation.OrganizationJobRiskAndFaultDescription.update", "بروزرسانی شرح سازمان کار خطر و خطا"},
        {"Organisation.OrganizationJobRiskAndFaultDescription.view", "مشاهده شرح سازمان کار خطر و خطا"},
        {"Organisation.OrganizationJobTaskDescription.create", "ایجاد شرح وظایف سازمانی"},
        {"Organisation.OrganizationJobTaskDescription.delete", "حذف شرح وظایف سازمانی"},
        {"Organisation.OrganizationJobTaskDescription.update", "بروزرسانی شرح وظایف سازمانی"},
        {"Organisation.OrganizationJobTaskDescription.view", "مشاهده شرح وظایف سازمانی"},
        {"Organisation.RelatedOrganizationJobDescription.create", "ایجاد مشاغل مرتبط"},
        {"Organisation.RelatedOrganizationJobDescription.delete", "حذف مشاغل مرتبط"},
        {"Organisation.RelatedOrganizationJobDescription.update", "بروزرسانی مشاغل مرتبط"},
        {"Organisation.RelatedOrganizationJobDescription.view", "مشاهده مشاغل مرتبط"},
        {"Organisation.OrganisationPositionSuggested.create", "ایجاد پیشنهاد پست"},
        {"Organisation.OrganisationPositionSuggested.delete", "حذف پیشنهاد پست"},
        {"Organisation.OrganisationPositionSuggested.update", "بروزرسانی پیشنهاد پست"},
        {"Organisation.OrganisationPositionSuggested.view", "مشاهده پیشنهاد پست"},
        {"Organisation.OrganisationJobSkillYearSetting.create", "ایجاد تنظیمات سال مهارت شغل"},
        {"Organisation.OrganisationJobSkillYearSetting.delete", "حذف تنظیمات سال مهارت شغل"},
        {"Organisation.OrganisationJobSkillYearSetting.update", "بروزرسانی تنظیمات سال مهارت شغل"},
        {"Organisation.OrganisationJobSkillYearSetting.view", "مشاهده تنظیمات سال مهارت شغل"},

        // PayRoll
        {"PayRoll.Bank.create", "ایجاد بانک"},
        {"PayRoll.Bank.delete", "حذف بانک"},
        {"PayRoll.Bank.update", "بروزرسانی بانک"},
        {"PayRoll.Bank.view", "مشاهده بانک"},
        {"PayRoll.BankBranch.create", "ایجاد شعبه بانک"},
        {"PayRoll.BankBranch.delete", "حذف شعبه بانک"},
        {"PayRoll.BankBranch.update", "بروزرسانی شعبه بانک"},
        {"PayRoll.BankBranch.view", "مشاهده شعبه بانک"},
        {"PayRoll.BankDiskette.create", "ایجاد دیسکت بانک"},
        {"PayRoll.BankDiskette.delete", "حذف دیسکت بانک"},
        {"PayRoll.BankDiskette.update", "بروزرسانی دیسکت بانک"},
        {"PayRoll.BankDiskette.view", "مشاهده دیسکت بانک"},
        {"PayRoll.BankDisketteTemplate.create", "ایجاد BankDisketteTemplate"},
        {"PayRoll.BankDisketteTemplate.delete", "حذف BankDisketteTemplate"},
        {"PayRoll.BankDisketteTemplate.update", "بروزرسانی BankDisketteTemplate"},
        {"PayRoll.BankDisketteTemplate.view", "مشاهده BankDisketteTemplate"},
        {"PayRoll.BankDisketteTemplateRow.create", "ایجاد ردیف قالب دیسکت بانک"},
        {"PayRoll.BankDisketteTemplateRow.delete", "حذف ردیف قالب دیسکت بانک"},
        {"PayRoll.BankDisketteTemplateRow.update", "بروزرسانی ردیف قالب دیسکت بانک"},
        {"PayRoll.BankDisketteTemplateRow.view", "مشاهده ردیف قالب دیسکت بانک"},
        {"PayRoll.BatchLog.view", "مشاهده لاگ عملیات گروهی"},
        {"PayRoll.BatchPayRollRequest.create", "ایجاد درخواست گروهی حقوق و دستمزد"},
        {"PayRoll.BatchPayRollRequest.delete", "حذف درخواست گروهی حقوق و دستمزد"},
        {"PayRoll.BatchPayRollRequest.update", "بروزرسانی درخواست گروهی حقوق و دستمزد"},
        {"PayRoll.BatchPayRollRequest.view", "مشاهده درخواست گروهی حقوق و دستمزد"},
        {"PayRoll.BatchPayRollRequestDetail.create", "ایجاد جزئیات درخواست گروهی حقوق و دستمزد"},
        {"PayRoll.BatchPayRollRequestDetail.delete", "حذف جزئیات درخواست گروهی حقوق و دستمزد"},
        {"PayRoll.BatchPayRollRequestDetail.update", "بروزرسانی جزئیات درخواست گروهی حقوق و دستمزد"},
        {"PayRoll.BatchPayRollRequestDetail.view", "مشاهده جزئیات درخواست گروهی حقوق و دستمزد"},
        {"PayRoll.BatchSettlementRequest.create", "ایجاد درخواست تسویه حساب گروهی"},
        {"PayRoll.BatchSettlementRequest.delete", "حذف درخواست تسویه حساب گروهی"},
        {"PayRoll.BatchSettlementRequest.update", "بروزرسانی درخواست تسویه حساب گروهی"},
        {"PayRoll.BatchSettlementRequest.view", "مشاهده درخواست تسویه حساب گروهی"},
        {"PayRoll.BatchSettlementRequestDetail.create", "ایجاد جزئیات درخواست تسویه حساب گروهی"},
        {"PayRoll.BatchSettlementRequestDetail.delete", "حذف جزئیات درخواست تسویه حساب گروهی"},
        {"PayRoll.BatchSettlementRequestDetail.update", "بروزرسانی جزئیات درخواست تسویه حساب گروهی"},
        {"PayRoll.BatchSettlementRequestDetail.view", "مشاهده جزئیات درخواست تسویه حساب گروهی"},
        {"PayRoll.BlackList.create", "ایجاد فهرست سیاه"},
        {"PayRoll.BlackList.delete", "حذف فهرست سیاه"},
        {"PayRoll.BlackList.update", "بروزرسانی فهرست سیاه"},
        {"PayRoll.BlackList.view", "مشاهده فهرست سیاه"},
        {"PayRoll.BlockedAccount.create", "ایجاد حساب های مسدود شده"},
        {"PayRoll.BlockedAccount.delete", "حذف حساب های مسدود شده"},
        {"PayRoll.BlockedAccount.update", "بروزرسانی حساب های مسدود شده"},
        {"PayRoll.BlockedAccount.view", "مشاهده حساب های مسدود شده"},
        {"PayRoll.CalclulationSetting.create", "ایجاد تنظیمات محاسبات"},
        {"PayRoll.CalclulationSetting.delete", "حذف تنظیمات محاسبات"},
        {"PayRoll.CalclulationSetting.update", "بروزرسانی تنظیمات محاسبات"},
        {"PayRoll.CalclulationSetting.view", "مشاهده تنظیمات محاسبات"},
        {"PayRoll.CostCenterFicheItem.create", "ایجاد عوامل حقوقی مرکز هزینه"},
        {"PayRoll.CostCenterFicheItem.delete", "حذف عوامل حقوقی مرکز هزینه"},
        {"PayRoll.CostCenterFicheItem.update", "بروزرسانی عوامل حقوقی مرکز هزینه"},
        {"PayRoll.CostCenterFicheItem.view", "مشاهده عوامل حقوقی مرکز هزینه"},
        {"PayRoll.Fiche.GetFicheCount", "مشاهده تعداد فیش های حقوقی"},
        {"PayRoll.Fiche.Get", "مشاهده فیش حقوقی"},
        {"PayRoll.Fiche.GetArear", "مشاهده فیش معوق"},
        {"PayRoll.Fiche.CalculateFiche", "محاسبه فیش موردی"},
        {"PayRoll.Fiche.BatchCalculation", "محاسبه دسته‌ای فیش‌ها"},
        {"PayRoll.Fiche.GetPagedData", "مشاهده فیش‌های صفحه‌بندی شده"},
        {"PayRoll.Fiche.GetArearFichePagedData", "مشاهده فیش‌های معوق صفحه‌بندی شده"},
        {"PayRoll.Fiche.GetArearArearsChangedFicheItem", "مشاهده اقلام تغییر یافته فیش معوق"},
        {"PayRoll.Arear.view", "مشاهده معوقه"},
        {"PayRoll.Arear.Get", "مشاهده معوقه"},
        {"PayRoll.Arear.GetByEmployee", "مشاهده معوقه‌های کارمند"},
        {"PayRoll.Arear.GetPagedData", "مشاهده فهرست معوقه‌ها"},
        {"PayRoll.Fiche.getCurrentPeriodAllFiche", "مشاهده همه فیش‌های دوره جاری"},
        {"PayRoll.Fiche.create", "ایجاد فیش حقوقی"},
        {"PayRoll.Fiche.delete", "حذف فیش حقوقی"},
        {"PayRoll.Fiche.update", "بروزرسانی فیش حقوقی"},
        {"PayRoll.Fiche.view", "مشاهده فیش حقوقی"},
        {"PayRoll.Fiche.Put", "بروزرسانی فیش"},
        {"PayRoll.Fiche.PrintPdf", "دانلود PDF فیش حقوقی"},
        {"PayRoll.Fiche.DeleteDraftFichesByPaymentPeriodId", "حذف تمام فیش های دوره جاری"},
        {"PayRoll.FunctionExcelDefinition.create", "ایجاد تعریف تابع اکسل"},
        {"PayRoll.FunctionExcelDefinition.delete", "حذف تعریف تابع اکسل"},
        {"PayRoll.FunctionExcelDefinition.update", "بروزرسانی تعریف تابع اکسل"},
        {"PayRoll.FunctionExcelDefinition.view", "مشاهده تعریف تابع اکسل"},
        {"PayRoll.InsuranceBranch.create", "ایجاد شعبه بیمه"},
        {"PayRoll.InsuranceBranch.delete", "حذف شعبه بیمه"},
        {"PayRoll.InsuranceBranch.update", "بروزرسانی شعبه بیمه"},
        {"PayRoll.InsuranceBranch.view", "مشاهده شعبه بیمه"},
        //{"PayRoll.InsuranceDiskette.UploadAndReadDbf", "UploadAndReadDbf"},
        {"PayRoll.InsuranceDiskette.create", "ایجاد دیسکت بیمه"},
        {"PayRoll.InsuranceDiskette.delete", "حذف دیسکت بیمه"},
        {"PayRoll.InsuranceDiskette.update", "بروزرسانی دیسکت بیمه"},
        {"PayRoll.InsuranceDiskette.view", "مشاهده دیسکت بیمه"},
        {"PayRoll.InsuranceDisketteItem.create", "ایجاد ردیف دیسکت بیمه"},
        {"PayRoll.InsuranceDisketteItem.delete", "حذف ردیف دیسکت بیمه"},
        {"PayRoll.InsuranceDisketteItem.update", "بروزرسانی ردیف دیسکت بیمه"},
        {"PayRoll.InsuranceDisketteItem.view", "مشاهده ردیف دیسکت بیمه"},
        {"PayRoll.InsuranceType.create", "ایجاد نوع بیمه"},
        {"PayRoll.InsuranceType.delete", "حذف نوع بیمه"},
        {"PayRoll.InsuranceType.update", "بروزرسانی نوع بیمه"},
        {"PayRoll.InsuranceType.view", "مشاهده نوع بیمه"},
        {"PayRoll.LoanType.create", "ایجاد نوع وام"},
        {"PayRoll.LoanType.delete", "حذف نوع وام"},
        {"PayRoll.LoanType.update", "بروزرسانی نوع وام"},
        {"PayRoll.LoanType.view", "مشاهده نوع وام"},
        {"PayRoll.OrganProperty.create", "ایجاد مشخصات سازمانی"},
        {"PayRoll.OrganProperty.delete", "حذف مشخصات سازمانی"},
        {"PayRoll.OrganProperty.update", "بروزرسانی مشخصات سازمانی"},
        {"PayRoll.OrganProperty.view", "مشاهده مشخصات سازمانی"},
        {"PayRoll.OrganisationEmployeeTypeFicheItem.create", "ایجاد OrganisationEmployeeTypeFicheItem"},
        {"PayRoll.OrganisationEmployeeTypeFicheItem.delete", "حذف OrganisationEmployeeTypeFicheItem"},
        {"PayRoll.OrganisationEmployeeTypeFicheItem.update", "بروزرسانی OrganisationEmployeeTypeFicheItem"},
        {"PayRoll.OrganisationEmployeeTypeFicheItem.view", "مشاهده OrganisationEmployeeTypeFicheItem"},
        {"PayRoll.OrganisationEmployeeTypeFundTypeDefinition.create", "ایجاد تعریف صندوق نوع استخدام"},
        {"PayRoll.OrganisationEmployeeTypeFundTypeDefinition.delete", "حذف تعریف صندوق نوع استخدام"},
        {"PayRoll.OrganisationEmployeeTypeFundTypeDefinition.update", "بروزرسانی تعریف صندوق نوع استخدام"},
        {"PayRoll.OrganisationEmployeeTypeFundTypeDefinition.view", "مشاهده تعریف صندوق نوع استخدام"},
        {"PayRoll.OrganisationFicheItem.create", "ایجاد اقلام فیش سازمان"},
        {"PayRoll.OrganisationFicheItem.delete", "حذف اقلام فیش سازمان"},
        {"PayRoll.OrganisationFicheItem.update", "بروزرسانی اقلام فیش سازمان"},
        {"PayRoll.OrganisationFicheItem.view", "مشاهده اقلام فیش سازمان"},
        {"PayRoll.PaymentPeriod.create", "ایجاد دوره های حقوقی"},
        {"PayRoll.PaymentPeriod.delete", "حذف دوره های حقوقی"},
        {"PayRoll.PaymentPeriod.update", "بروزرسانی دوره های حقوقی"},
        {"PayRoll.PaymentPeriod.view", "مشاهده دوره های حقوقی"},
        {"PayRoll.PaymentPeriod.GetcurrentUserDefaultPaymentPeiodId", "مشاهده دوره محاسبه حقوق پیش فرض کاربر جاری"},
        {"PayRoll.PaymentPeriod.ClosePeriodAndMarkFichesPayed", "بستن دوره و تغییر وضعیت فیش‌ها به پرداخت شده"},
        {"PayRoll.PaymentType.create", "ایجاد نوع پرداخت"},
        {"PayRoll.PaymentType.delete", "حذف نوع پرداخت"},
        {"PayRoll.PaymentType.update", "بروزرسانی نوع پرداخت"},
        {"PayRoll.PaymentType.view", "مشاهده نوع پرداخت"},
        {"PayRoll.DeductionType.create", "ایجاد نوع کسور"},
        {"PayRoll.DeductionType.delete", "حذف نوع کسور"},
        {"PayRoll.DeductionType.update", "بروزرسانی نوع کسور"},
        {"PayRoll.DeductionType.view", "مشاهده نوع کسور"},
        {"PayRoll.PayrollOrder.create", "ایجاد احکام در حقوق و دستمزد"},
        {"PayRoll.PayrollOrder.delete", "حذف احکام در حقوق و دستمزد"},
        {"PayRoll.PayrollOrder.update", "بروزرسانی احکام در حقوق و دستمزد"},
        {"PayRoll.PayrollOrder.view", "مشاهده احکام در حقوق و دستمزد"},
        {"PayRoll.PersonnelFicheItem.create", "ایجاد PersonnelFicheItem"},
        {"PayRoll.PersonnelFicheItem.delete", "حذف PersonnelFicheItem"},
        {"PayRoll.PersonnelFicheItem.update", "بروزرسانی PersonnelFicheItem"},
        {"PayRoll.PersonnelFicheItem.view", "مشاهده PersonnelFicheItem"},
        {"PayRoll.PersonnelFicheItem.GetPaymentDetailsByFicheItemId", "مشاهده جزئیات پرداخت قلم اختصاصی فرد"},
        {"PayRoll.PersonnelFunction.create", "ایجاد کارکرد کارکنان"},
        {"PayRoll.PersonnelFunction.delete", "حذف کارکرد کارکنان"},
        {"PayRoll.PersonnelFunction.update", "بروزرسانی کارکرد کارکنان"},
        {"PayRoll.PersonnelFunction.view", "مشاهده کارکرد کارکنان"},
        {"PayRoll.PersonnelFunction.BulkUpdate", "بروز رسانی گروهی کارکرد ها"},
        {"PayRoll.PersonnelFunction.GetFunctionBulkCartable", "مشاهده کارتابل کارکرد بر اساس دسترسی ها"},
        {"PayRoll.PersonnelFunction.GetFilteredPersonnelFunctions", "مشاهده کارکرد کارکنان کلی با فیلتر"},
        {"PayRoll.PersonnelFunctionVisible.create", "ایجاد نمایش‌پذیری کارکرد کارکنان"},
        {"PayRoll.PersonnelFunctionVisible.delete", "حذف نمایش‌پذیری کارکرد کارکنان"},
        {"PayRoll.PersonnelFunctionVisible.update", "بروزرسانی نمایش‌پذیری کارکرد کارکنان"},
        {"PayRoll.PersonnelFunctionVisible.view", "مشاهده نمایش‌پذیری کارکرد کارکنان"},
        {"PayRoll.PersonnelFunctionExcelFile.create", "ایجاد فایل اکسل کارکرد"},
        {"PayRoll.PersonnelFunctionExcelFile.delete", "حذف فایل اکسل کارکرد"},
        {"PayRoll.PersonnelFunctionExcelFile.update", "بروزرسانی فایل اکسل کارکرد"},
        {"PayRoll.PersonnelFunctionExcelFile.view", "مشاهده فایل اکسل کارکرد"},
        {"PayRoll.PersonnelLoan.create", "ایجاد PersonnelLoan"},
        {"PayRoll.PersonnelLoan.delete", "حذف PersonnelLoan"},
        {"PayRoll.PersonnelLoan.update", "بروزرسانی PersonnelLoan"},
        {"PayRoll.PersonnelLoan.view", "مشاهده PersonnelLoan"},
        {"PayRoll.PersonnelProperty.create", "ایجاد PersonnelProperty"},
        {"PayRoll.PersonnelProperty.delete", "حذف PersonnelProperty"},
        {"PayRoll.PersonnelProperty.update", "بروزرسانی PersonnelProperty"},
        {"PayRoll.PersonnelProperty.view", "مشاهده PersonnelProperty"},
        {"PayRoll.Tax.create", "ایجاد مالیات"},
        {"PayRoll.Tax.delete", "حذف مالیات"},
        {"PayRoll.Tax.update", "بروزرسانی مالیات"},
        {"PayRoll.Tax.view", "مشاهده مالیات"},
        {"PayRoll.TaxCoefficientItem.create", "ایجاد TaxCoefficientItem"},
        {"PayRoll.TaxCoefficientItem.delete", "حذف TaxCoefficientItem"},
        {"PayRoll.TaxCoefficientItem.update", "بروزرسانی TaxCoefficientItem"},
        {"PayRoll.TaxCoefficientItem.view", "مشاهده TaxCoefficientItem"},
        {"PayRoll.TaxDiskette.create", "ایجاد دیسکت مالیات"},
        {"PayRoll.TaxDiskette.delete", "حذف دیسکت مالیات"},
        {"PayRoll.TaxDiskette.update", "بروزرسانی دیسکت مالیات"},
        {"PayRoll.TaxDiskette.view", "مشاهده دیسکت مالیات"},
        {"PayRoll.TaxTable.create", "ایجاد جدول مالیاتی"},
        {"PayRoll.TaxTable.delete", "حذف جدول مالیاتی"},
        {"PayRoll.TaxTable.update", "بروزرسانی جدول مالیاتی"},
        {"PayRoll.TaxTable.view", "مشاهده جدول مالیاتی"},
        {"PayRoll.TaxNonCashPayment.create", "ایجاد پرداخت های غیر نقدی"},
        {"PayRoll.TaxNonCashPayment.delete", "حذف پرداخت های غیر نقدی"},
        {"PayRoll.TaxNonCashPayment.update", "بروزرسانی پرداخت های غیر نقدی"},
        {"PayRoll.TaxNonCashPayment.view", "مشاهده پرداخت های غیر نقدی"},
        {"PayRoll.OrganisationEmployeeTypeCoefficientBonusWageItem.create", "ایجاد ضرایب/آیتم مزد نوع استخدام"},
        {"PayRoll.OrganisationEmployeeTypeCoefficientBonusWageItem.delete", "حذف ضرایب/آیتم مزد نوع استخدام"},
        {"PayRoll.OrganisationEmployeeTypeCoefficientBonusWageItem.update", "بروزرسانی ضرایب/آیتم مزد نوع استخدام"},
        {"PayRoll.OrganisationEmployeeTypeCoefficientBonusWageItem.view", "مشاهده ضرایب/آیتم مزد نوع استخدام"},
        {"PayRoll.TaminInsuranceJobList.create", "ایجاد مشاغل تامین اجتماعی"},
        {"PayRoll.TaminInsuranceJobList.delete", "حذف مشاغل تامین اجتماعی"},
        {"PayRoll.TaminInsuranceJobList.update", "بروزرسانی مشاغل تامین اجتماعی"},
        {"PayRoll.TaminInsuranceJobList.view", "مشاهده مشاغل تامین اجتماعی"},
        {"PayRoll.PaymentPeriodEmployeeBonus.create", "ایجاد"},
        {"PayRoll.PaymentPeriodEmployeeBonus.delete", "حذف"},
        {"PayRoll.PaymentPeriodEmployeeBonus.update", "بروزرسانی"},
        {"PayRoll.PaymentPeriodEmployeeBonus.view", "مشاهده"},
        {"PayRoll.MinimumMonthlyWage.create", "ایجاد حداقل دستمزد ماهانه"},
        {"PayRoll.MinimumMonthlyWage.delete", "حذف حداقل دستمزد ماهانه"},
        {"PayRoll.MinimumMonthlyWage.update", "بروزرسانی حداقل دستمزد ماهانه"},
        {"PayRoll.MinimumMonthlyWage.view", "مشاهده حداقل دستمزد ماهانه"},


        // Report
        {"Report.DynamicReport.DownloadDynamicReport", "گرفتن و دانلود گزارش"},
        {"Report.DynamicReport.create", "ایجاد گزارش پویا"},
        {"Report.DynamicReport.delete", "حذف گزارش پویا"},
        {"Report.DynamicReport.update", "بروزرسانی گزارش پویا"},
        {"Report.DynamicReport.view", "مشاهده گزارش پویا"},
        {"Report.FieldDataType.create", "ایجاد نوع داده فیلد"},
        {"Report.FieldDataType.delete", "حذف نوع داده فیلد"},
        {"Report.FieldDataType.update", "بروزرسانی نوع داده فیلد"},
        {"Report.FieldDataType.view", "مشاهده نوع داده فیلد"},
        {"Report.FieldOperator.create", "ایجاد عملگر فیلد"},
        {"Report.FieldOperator.delete", "حذف عملگر فیلد"},
        {"Report.FieldOperator.update", "بروزرسانی عملگر فیلد"},
        {"Report.FieldOperator.view", "مشاهده عملگر فیلد"},
        {"Report.ReportableEntity.create", "ایجاد موجودیت قابل گزارش"},
        {"Report.ReportableEntity.delete", "حذف موجودیت قابل گزارش"},
        {"Report.ReportableEntity.update", "بروزرسانی موجودیت قابل گزارش"},
        {"Report.ReportableEntity.view", "مشاهده موجودیت قابل گزارش"},
        {"Report.ReportableField.create", "ایجاد فیلد قابل گزارش"},
        {"Report.ReportableField.delete", "حذف فیلد قابل گزارش"},
        {"Report.ReportableField.update", "بروزرسانی فیلد قابل گزارش"},
        {"Report.ReportableField.view", "مشاهده فیلد قابل گزارش"},
        {"Report.PayLocationProgressReport.create", "ایجاد گزارش پیشرفت محل پرداخت"},
        {"Report.PayLocationProgressReport.delete", "حذف گزارش پیشرفت محل پرداخت"},
        {"Report.PayLocationProgressReport.update", "بروزرسانی گزارش پیشرفت محل پرداخت"},
        {"Report.PayLocationProgressReport.view", "مشاهده گزارش پیشرفت محل پرداخت"},
        {"Report.ReportBuilder.view", "مشاهده گزارش ساز پویا"},
        {"Report.ReportBuilder.ScanAndPopulateEntities", "اسکن و ثبت خودکار جداول سیستم"},
        {"Report.MissingDataAnalysis.view", "مشاهده تحلیل اطلاعات ناقص"},
        {"Report.Statistics.view", "مشاهده آمار سازمانی"},
        {"Report.Statistics.TotalEmployees", "مشاهده تعداد کل کارکنان"},

        // SystemSetting
        {"SystemSetting.OrganisationFormula.create", "ایجاد فرمول های سازمان"},
        {"SystemSetting.OrganisationFormula.delete", "حذف فرمول های سازمان"},
        {"SystemSetting.OrganisationFormula.update", "بروزرسانی فرمول های سازمان"},
        {"SystemSetting.OrganisationFormula.view", "مشاهده فرمول های سازمان"},
        {"SystemSetting.OrganisationAgentOfPunishmentEncourage.create", "ایجاد OrganisationAgentOfPunishmentEncourage"},
        {"SystemSetting.OrganisationAgentOfPunishmentEncourage.delete", "حذف OrganisationAgentOfPunishmentEncourage"},
        {"SystemSetting.OrganisationAgentOfPunishmentEncourage.update", "بروزرسانی OrganisationAgentOfPunishmentEncourage"},
        {"SystemSetting.OrganisationAgentOfPunishmentEncourage.view", "مشاهده OrganisationAgentOfPunishmentEncourage"},
        {"SystemSetting.OrganisationAgentOfPunishmentEncourageScoreInterval.create", "ایجاد بازه تنبیه و تشویق"},
        {"SystemSetting.OrganisationAgentOfPunishmentEncourageScoreInterval.delete", "حذف بازه تنبیه و تشویق"},
        {"SystemSetting.OrganisationAgentOfPunishmentEncourageScoreInterval.update", "بروزرسانی بازه تنبیه و تشویق"},
        {"SystemSetting.OrganisationAgentOfPunishmentEncourageScoreInterval.view", "مشاهده بازه تنبیه و تشویق"},
        {"SystemSetting.OrganisationCoefficient.create", "ایجاد ضرائب سازمان"},
        {"SystemSetting.OrganisationCoefficient.delete", "حذف ضرائب سازمان"},
        {"SystemSetting.OrganisationCoefficient.update", "بروزرسانی ضرائب سازمان"},
        {"SystemSetting.OrganisationCoefficient.view", "مشاهده ضرائب سازمان"},
        {"SystemSetting.OrganisationCostCenter.create", "ایجاد مرکز هزینه های سازمان"},
        {"SystemSetting.OrganisationCostCenter.delete", "حذف مرکز هزینه های سازمان"},
        {"SystemSetting.OrganisationCostCenter.update", "بروزرسانی مرکز هزینه های سازمان"},
        {"SystemSetting.OrganisationCostCenter.view", "مشاهده مرکز هزینه های سازمان"},
        {"SystemSetting.OrganisationEmployeeStatus.create", "ایجاد وضعیت استخدام های سازمان"},
        {"SystemSetting.OrganisationEmployeeStatus.delete", "حذف وضعیت استخدام های سازمان"},
        {"SystemSetting.OrganisationEmployeeStatus.update", "بروزرسانی وضعیت استخدام های سازمان"},
        {"SystemSetting.OrganisationEmployeeStatus.view", "مشاهده وضعیت استخدام های سازمان"},
        {"SystemSetting.OrganisationEmployeeType.create", "ایجاد نوع استخدام های سازمان"},
        {"SystemSetting.OrganisationEmployeeType.delete", "حذف نوع استخدام های سازمان"},
        {"SystemSetting.OrganisationEmployeeType.update", "بروزرسانی نوع استخدام های سازمان"},
        {"SystemSetting.OrganisationEmployeeType.view", "مشاهده نوع استخدام های سازمان"},
        {"SystemSetting.OrganisationEmployeeTypeCoefficient.create", "ایجاد ضرائب نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeCoefficient.delete", "حذف ضرائب نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeCoefficient.update", "بروزرسانی ضرائب نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeCoefficient.view", "مشاهده ضرائب نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeMRT.create", "ایجاد OrganisationEmployeeTypeMRT"},
        {"SystemSetting.OrganisationEmployeeTypeMRT.delete", "حذف OrganisationEmployeeTypeMRT"},
        {"SystemSetting.OrganisationEmployeeTypeMRT.update", "بروزرسانی OrganisationEmployeeTypeMRT"},
        {"SystemSetting.OrganisationEmployeeTypeMRT.view", "مشاهده OrganisationEmployeeTypeMRT"},
        {"SystemSetting.OrganisationEmployeeTypeOrderType.create", "ایجاد حکم های نوع استخدام سازمان"},
        {"SystemSetting.OrganisationEmployeeTypeOrderType.delete", "حذف حکم های نوع استخدام سازمان"},
        {"SystemSetting.OrganisationEmployeeTypeOrderType.update", "بروزرسانی حکم های نوع استخدام سازمان"},
        {"SystemSetting.OrganisationEmployeeTypeOrderType.view", "مشاهده حکم های نوع استخدام سازمان"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCanChange.create", "ایجاد فیلد های استخدامی تغییر پذیر"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCanChange.delete", "حذف فیلد های استخدامی تغییر پذیر"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCanChange.update", "بروزرسانی فیلد های استخدامی تغییر پذیر"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCanChange.view", "مشاهده فیلد های استخدامی تغییر پذیر"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCheck.create", "ایجاد فرمول های چک"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCheck.delete", "حذف فرمول های چک"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCheck.update", "بروزرسانی فرمول های چک"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCheck.view", "مشاهده فرمول های چک"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCoefficient.create", "ایجاد ضرائب حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCoefficient.delete", "حذف ضرائب حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCoefficient.update", "بروزرسانی ضرائب حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeCoefficient.view", "مشاهده ضرائب حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeDescription.create", "ایجاد شرح حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeDescription.delete", "حذف شرح حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeDescription.update", "بروزرسانی شرح حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeDescription.view", "مشاهده شرح حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeSummaryCalc.create", "ایجاد خلاصه حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeSummaryCalc.delete", "حذف خلاصه حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeSummaryCalc.update", "بروزرسانی خلاصه حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeSummaryCalc.view", "مشاهده خلاصه حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeWageItem.create", "ایجاد تنظیمات قلم های حقوقی در حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeWageItem.delete", "حذف تنظیمات قلم های حقوقی در حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeWageItem.update", "بروزرسانی تنظیمات قلم های حقوقی در حکم"},
        {"SystemSetting.OrganisationEmployeeTypeOrderTypeWageItem.view", "مشاهده تنظیمات قلم های حقوقی در حکم"},
        {"SystemSetting.OrganisationEmployeeTypeWageItem.create", "ایجاد اقلام حقوقی نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeWageItem.delete", "حذف اقلام حقوقی نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeWageItem.update", "بروزرسانی اقلام حقوقی نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeWageItem.view", "مشاهده اقلام حقوقی نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeSettlementItem.create", "ایجاد آیتم تسویه نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeSettlementItem.delete", "حذف آیتم تسویه نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeSettlementItem.update", "بروزرسانی آیتم تسویه نوع استخدام"},
        {"SystemSetting.OrganisationEmployeeTypeSettlementItem.view", "مشاهده آیتم تسویه نوع استخدام"},
        {"SystemSetting.OrganisationMRT.create", "ایجاد OrganisationMRT"},
        {"SystemSetting.OrganisationMRT.delete", "حذف OrganisationMRT"},
        {"SystemSetting.OrganisationMRT.update", "بروزرسانی OrganisationMRT"},
        {"SystemSetting.OrganisationMRT.view", "مشاهده OrganisationMRT"},
        {"SystemSetting.OrganisationOrderType.create", "ایجاد نوع حکم های سازمان"},
        {"SystemSetting.OrganisationOrderType.delete", "حذف نوع حکم های سازمان"},
        {"SystemSetting.OrganisationOrderType.update", "بروزرسانی نوع حکم های سازمان"},
        {"SystemSetting.OrganisationOrderType.view", "مشاهده نوع حکم های سازمان"},
        {"SystemSetting.OrganisationPeymanRow.create", "ایجاد OrganisationPeymanRow"},
        {"SystemSetting.OrganisationPeymanRow.delete", "حذف OrganisationPeymanRow"},
        {"SystemSetting.OrganisationPeymanRow.update", "بروزرسانی OrganisationPeymanRow"},
        {"SystemSetting.OrganisationPeymanRow.view", "مشاهده OrganisationPeymanRow"},
        {"SystemSetting.OrganisationSetting.create", "ایجاد تنظیمات سازمان"},
        {"SystemSetting.OrganisationSetting.delete", "حذف تنظیمات سازمان"},
        {"SystemSetting.OrganisationSetting.update", "بروزرسانی تنظیمات سازمان"},
        {"SystemSetting.OrganisationSetting.view", "مشاهده تنظیمات سازمان"},
        {"SystemSetting.OrganisationWageItem.create", "ایجاد عوامل حقوقی سازمان"},
        {"SystemSetting.OrganisationWageItem.delete", "حذف عوامل حقوقی سازمان"},
        {"SystemSetting.OrganisationWageItem.update", "بروزرسانی عوامل حقوقی سازمان"},
        {"SystemSetting.OrganisationWageItem.view", "مشاهده عوامل حقوقی سازمان"},
        {"SystemSetting.OrganisationSettlementCause.create", "ایجاد علت تسویه حساب سازمان"},
        {"SystemSetting.OrganisationSettlementCause.delete", "حذف علت تسویه حساب سازمان"},
        {"SystemSetting.OrganisationSettlementCause.update", "بروزرسانی علت تسویه حساب سازمان"},
        {"SystemSetting.OrganisationSettlementCause.view", "مشاهده علت تسویه حساب سازمان"},
        {"SystemSetting.OrganisationSettlementItem.create", "ایجاد آیتم تسویه حساب سازمان"},
        {"SystemSetting.OrganisationSettlementItem.delete", "حذف آیتم تسویه حساب سازمان"},
        {"SystemSetting.OrganisationSettlementItem.update", "بروزرسانی آیتم تسویه حساب سازمان"},
        {"SystemSetting.OrganisationSettlementItem.view", "مشاهده آیتم تسویه حساب سازمان"},

  
        // WorkFlow
        {"WorkFlow.Action.create", "ایجاد عملیات"},
        {"WorkFlow.Action.delete", "حذف عملیات"},
        {"WorkFlow.Action.update", "بروزرسانی عملیات"},
        {"WorkFlow.Action.view", "مشاهده عملیات"},
        {"WorkFlow.ActivityTemplate.create", "ایجاد قالب فعالیت"},
        {"WorkFlow.ActivityTemplate.delete", "حذف قالب فعالیت"},
        {"WorkFlow.ActivityTemplate.update", "بروزرسانی قالب فعالیت"},
        {"WorkFlow.ActivityTemplate.view", "مشاهده قالب فعالیت"},
        {"WorkFlow.Definition.create", "ایجاد تعاریف"},
        {"WorkFlow.Definition.delete", "حذف تعاریف"},
        {"WorkFlow.Definition.update", "بروزرسانی تعاریف"},
        {"WorkFlow.Definition.view", "مشاهده تعاریف"},
        {"WorkFlow.Definition.GetDiagram", "مشاهده نمودار طراحی گردش کار"},
        {"WorkFlow.WorkFlow.GetAsKeyValuePairByWorkFlowTypeId", "مشاهده گردش کارهای نوع گردش کار"},
        {"WorkFlow.Node.create", "ایجاد گره"},
        {"WorkFlow.Node.delete", "حذف گره"},
        {"WorkFlow.Node.update", "بروزرسانی گره"},
        {"WorkFlow.Node.view", "مشاهده گره"},
        {"WorkFlow.Node.GetAsKeyValuePairByWorkFlowId", "مشاهده گره‌های گردش کار"},
        {"WorkFlow.NodeUserRel.create", "ایجاد NodeUserRel"},
        {"WorkFlow.NodeUserRel.delete", "حذف NodeUserRel"},
        {"WorkFlow.NodeUserRel.update", "بروزرسانی NodeUserRel"},
        {"WorkFlow.NodeUserRel.view", "مشاهده NodeUserRel"},
        {"WorkFlow.NodeRoleRel.create", "ایجاد ارتباط گره با نقش"},
        {"WorkFlow.NodeRoleRel.delete", "حذف ارتباط گره با نقش"},
        {"WorkFlow.NodeRoleRel.update", "بروزرسانی ارتباط گره با نقش"},
        {"WorkFlow.NodeRoleRel.view", "مشاهده ارتباط گره با نقش"},
        {"WorkFlow.UserSignature.create", "ایجاد امضا کاربر"},
        {"WorkFlow.UserSignature.delete", "حذف امضا کاربر"},
        {"WorkFlow.UserSignature.update", "بروزرسانی امضا کاربر"},
        {"WorkFlow.UserSignature.view", "مشاهده امضا کاربر"},
        {"WorkFlow.WorkFlow.create", "ایجاد گردش کار"},
        {"WorkFlow.WorkFlow.delete", "حذف گردش کار"},
        {"WorkFlow.WorkFlow.update", "بروزرسانی گردش کار"},
        {"WorkFlow.WorkFlow.view", "مشاهده گردش کار"},
        {"WorkFlow.WorkFlowInstance.create", "ایجاد نمونه گردش کار"},
        {"WorkFlow.WorkFlowInstance.delete", "حذف نمونه گردش کار"},
        {"WorkFlow.WorkFlowInstance.update", "بروزرسانی نمونه گردش کار"},
        {"WorkFlow.WorkFlowInstance.view", "مشاهده نمونه گردش کار"},
        {"WorkFlow.WorkFlowInstance.GetCartableArchive", "مشاهده آرشیو کارتابل گردش کار"},
        {"WorkFlow.WorkFlowInstance.batchAction", "عملیات گروهی نمونه گردش کار"},
        {"WorkFlow.WorkFlowType.create", "ایجاد نوع گردش کار"},
        {"WorkFlow.WorkFlowType.delete", "حذف نوع گردش کار"},
        {"WorkFlow.WorkFlowType.update", "بروزرسانی نوع گردش کار"},
        {"WorkFlow.WorkFlowType.view", "مشاهده نوع گردش کار"},

        // baseInfo
        {"baseInfo.AttendanceHoliday.create", "ایجاد تعطیلات حضور و غیاب"},
        {"baseInfo.AttendanceHoliday.delete", "حذف تعطیلات حضور و غیاب"},
        {"baseInfo.AttendanceHoliday.update", "بروزرسانی تعطیلات حضور و غیاب"},
        {"baseInfo.AttendanceHoliday.view", "مشاهده تعطیلات حضور و غیاب"},
        {"baseInfo.AgentOfPunishmentEncourage.create", "ایجاد عامل تنبیه و تشویق"},
        {"baseInfo.AgentOfPunishmentEncourage.delete", "حذف عامل تنبیه و تشویق"},
        {"baseInfo.AgentOfPunishmentEncourage.update", "بروزرسانی عامل تنبیه و تشویق"},
        {"baseInfo.AgentOfPunishmentEncourage.view", "مشاهده عامل تنبیه و تشویق"},
        {"baseInfo.AgentOfPunishmentEncourageGroup.create", "ایجاد عامل تنبیه و تشویق"},
        {"baseInfo.AgentOfPunishmentEncourageGroup.delete", "حذف عامل تنبیه و تشویق"},
        {"baseInfo.AgentOfPunishmentEncourageGroup.update", "بروزرسانی عامل تنبیه و تشویق"},
        {"baseInfo.AgentOfPunishmentEncourageGroup.view", "مشاهده عامل تنبیه و تشویق"},
        {"baseInfo.BaseTable.create", "ایجاد جدول پایه"},
        {"baseInfo.BaseTable.delete", "حذف جدول پایه"},
        {"baseInfo.BaseTable.update", "بروزرسانی جدول پایه"},
        {"baseInfo.BaseTable.view", "مشاهده جدول پایه"},
        {"baseInfo.BaseTableValue.create", "ایجاد مقدار جدول پایه"},
        {"baseInfo.BaseTableValue.delete", "حذف مقدار جدول پایه"},
        {"baseInfo.BaseTableValue.update", "بروزرسانی مقدار جدول پایه"},
        {"baseInfo.BaseTableValue.view", "مشاهده مقدار جدول پایه"},
        {"baseInfo.Coefficient.create", "ایجاد ضرایب"},
        {"baseInfo.Coefficient.delete", "حذف ضرایب"},
        {"baseInfo.Coefficient.update", "بروزرسانی ضرایب"},
        {"baseInfo.Coefficient.view", "مشاهده ضرایب"},
        {"baseInfo.EducationField.create", "ایجاد رشته تحصیلی"},
        {"baseInfo.EducationField.delete", "حذف رشته تحصیلی"},
        {"baseInfo.EducationField.update", "بروزرسانی رشته تحصیلی"},
        {"baseInfo.EducationField.view", "مشاهده رشته تحصیلی"},
        {"baseInfo.EducationGrade.create", "ایجاد مقطع تحصیلی"},
        {"baseInfo.EducationGrade.delete", "حذف مقطع تحصیلی"},
        {"baseInfo.EducationGrade.update", "بروزرسانی مقطع تحصیلی"},
        {"baseInfo.EducationGrade.view", "مشاهده مقطع تحصیلی"},
        {"baseInfo.EducationGroup.create", "ایجاد گروه تحصیلی"},
        {"baseInfo.EducationGroup.delete", "حذف گروه تحصیلی"},
        {"baseInfo.EducationGroup.update", "بروزرسانی گروه تحصیلی"},
        {"baseInfo.EducationGroup.view", "مشاهده گروه تحصیلی"},
        {"baseInfo.EducationOrientation.create", "ایجاد گرایش تحصیلی"},
        {"baseInfo.EducationOrientation.delete", "حذف گرایش تحصیلی"},
        {"baseInfo.EducationOrientation.update", "بروزرسانی گرایش تحصیلی"},
        {"baseInfo.EducationOrientation.view", "مشاهده گرایش تحصیلی"},
        {"baseInfo.EmployeeStatus.create", "ایجاد وضعیت استخدام"},
        {"baseInfo.EmployeeStatus.delete", "حذف وضعیت استخدام"},
        {"baseInfo.EmployeeStatus.update", "بروزرسانی وضعیت استخدام"},
        {"baseInfo.EmployeeStatus.view", "مشاهده وضعیت استخدام"},
        {"baseInfo.HistoryType.create", "ایجاد نوع سابقه"},
        {"baseInfo.HistoryType.delete", "حذف نوع سابقه"},
        {"baseInfo.HistoryType.update", "بروزرسانی نوع سابقه"},
        {"baseInfo.HistoryType.view", "مشاهده نوع سابقه"},
        {"baseInfo.MeasurementUnit.create", "ایجاد واحد سنجش"},
        {"baseInfo.MeasurementUnit.delete", "حذف واحد سنجش"},
        {"baseInfo.MeasurementUnit.update", "بروزرسانی واحد سنجش"},
        {"baseInfo.MeasurementUnit.view", "مشاهده واحد سنجش"},
        {"baseInfo.LeaveType.create", "ایجاد نوع مرخصی"},
        {"baseInfo.LeaveType.delete", "حذف نوع مرخصی"},
        {"baseInfo.LeaveType.update", "بروزرسانی نوع مرخصی"},
        {"baseInfo.LeaveType.view", "مشاهده نوع مرخصی"},
        {"baseInfo.EmployeeStatusGroup.create", "ایجاد EmployeeStatusGroup"},
        {"baseInfo.EmployeeStatusGroup.delete", "حذف EmployeeStatusGroup"},
        {"baseInfo.EmployeeStatusGroup.update", "بروزرسانی EmployeeStatusGroup"},
        {"baseInfo.EmployeeStatusGroup.view", "مشاهده EmployeeStatusGroup"},
        {"baseInfo.EmployeeType.create", "ایجاد نوع استخدام"},
        {"baseInfo.EmployeeType.delete", "حذف نوع استخدام"},
        {"baseInfo.EmployeeType.update", "بروزرسانی نوع استخدام"},
        {"baseInfo.EmployeeType.view", "مشاهده نوع استخدام"},
        {"baseInfo.EmployeeTypeGroup.create", "ایجاد EmployeeTypeGroup"},
        {"baseInfo.EmployeeTypeGroup.delete", "حذف EmployeeTypeGroup"},
        {"baseInfo.EmployeeTypeGroup.update", "بروزرسانی EmployeeTypeGroup"},
        {"baseInfo.EmployeeTypeGroup.view", "مشاهده EmployeeTypeGroup"},
        {"baseInfo.Formula.create", "ایجاد فرمول ها"},
        {"baseInfo.Formula.delete", "حذف فرمول ها"},
        {"baseInfo.Formula.update", "بروزرسانی فرمول ها"},
        {"baseInfo.Formula.view", "مشاهده فرمول ها"},
        {"baseInfo.InsurancePosition.create", "ایجاد بیمه - پست"},
        {"baseInfo.InsurancePosition.delete", "حذف بیمه - پست"},
        {"baseInfo.InsurancePosition.update", "بروزرسانی بیمه - پست"},
        {"baseInfo.InsurancePosition.view", "مشاهده بیمه - پست"},
        {"baseInfo.Job.create", "ایجاد شغل"},
        {"baseInfo.Job.delete", "حذف شغل"},
        {"baseInfo.Job.update", "بروزرسانی شغل"},
        {"baseInfo.Job.view", "مشاهده شغل"},
        {"baseInfo.JobCategory.create", "ایجاد JobCategory"},
        {"baseInfo.JobCategory.delete", "حذف JobCategory"},
        {"baseInfo.JobCategory.update", "بروزرسانی JobCategory"},
        {"baseInfo.JobCategory.view", "مشاهده JobCategory"},
        {"baseInfo.JobGroup.create", "ایجاد JobGroup"},
        {"baseInfo.JobGroup.delete", "حذف JobGroup"},
        {"baseInfo.JobGroup.update", "بروزرسانی JobGroup"},
        {"baseInfo.JobGroup.view", "مشاهده JobGroup"},
        {"baseInfo.JobSeries.create", "ایجاد JobSeries"},
        {"baseInfo.JobSeries.delete", "حذف JobSeries"},
        {"baseInfo.JobSeries.update", "بروزرسانی JobSeries"},
        {"baseInfo.JobSeries.view", "مشاهده JobSeries"},
        {"baseInfo.Log.create", "ایجاد لاگ ها"},
        {"baseInfo.Log.delete", "حذف لاگ ها"},
        {"baseInfo.Log.update", "بروزرسانی لاگ ها"},
        {"baseInfo.Log.view", "مشاهده لاگ ها"},
        {"baseInfo.OrderStatus.create", "ایجاد وضعیت احکام"},
        {"baseInfo.OrderStatus.delete", "حذف وضعیت احکام"},
        {"baseInfo.OrderStatus.update", "بروزرسانی وضعیت احکام"},
        {"baseInfo.OrderStatus.view", "مشاهده وضعیت احکام"},
        {"baseInfo.OrderType.create", "ایجاد نوع حکم"},
        {"baseInfo.OrderType.delete", "حذف نوع حکم"},
        {"baseInfo.OrderType.update", "بروزرسانی نوع حکم"},
        {"baseInfo.OrderType.view", "مشاهده نوع حکم"},
        {"baseInfo.OrderTypeGroup.create", "ایجاد گروه احکام"},
        {"baseInfo.OrderTypeGroup.delete", "حذف گروه احکام"},
        {"baseInfo.OrderTypeGroup.update", "بروزرسانی گروه احکام"},
        {"baseInfo.OrderTypeGroup.view", "مشاهده گروه احکام"},
        {"baseInfo.OrganizationType.create", "ایجاد نوع سازمان"},
        {"baseInfo.OrganizationType.delete", "حذف نوع سازمان"},
        {"baseInfo.OrganizationType.update", "بروزرسانی نوع سازمان"},
        {"baseInfo.OrganizationType.view", "مشاهده نوع سازمان"},
        {"baseInfo.Places.create", "ایجاد محل ها"},
        {"baseInfo.Places.delete", "حذف محل ها"},
        {"baseInfo.Places.update", "بروزرسانی محل ها"},
        {"baseInfo.Places.view", "مشاهده محل ها"},
        {"baseInfo.Position.create", "ایجاد پست ها"},
        {"baseInfo.Position.delete", "حذف پست ها"},
        {"baseInfo.Position.update", "بروزرسانی پست ها"},
        {"baseInfo.Position.view", "مشاهده پست ها"},
        {"baseInfo.PositionType.create", "ایجاد نوع پست"},
        {"baseInfo.PositionType.delete", "حذف نوع پست"},
        {"baseInfo.PositionType.update", "بروزرسانی نوع پست"},
        {"baseInfo.PositionType.view", "مشاهده نوع پست"},
        {"baseInfo.Project.create", "ایجاد پروژه ها"},
        {"baseInfo.Project.delete", "حذف پروژه ها"},
        {"baseInfo.Project.update", "بروزرسانی پروژه ها"},
        {"baseInfo.Project.view", "مشاهده پروژه ها"},
        {"baseInfo.TaxExemptionType.create", "ایجاد نوع معافیت مالیاتی"},
        {"baseInfo.TaxExemptionType.delete", "حذف نوع معافیت مالیاتی"},
        {"baseInfo.TaxExemptionType.update", "بروزرسانی نوع معافیت مالیاتی"},
        {"baseInfo.TaxExemptionType.view", "مشاهده نوع معافیت مالیاتی"},
        {"baseInfo.SettlementItem.create", "ایجاد آیتم تسویه"},
        {"baseInfo.SettlementItem.delete", "حذف آیتم تسویه"},
        {"baseInfo.SettlementItem.update", "بروزرسانی آیتم تسویه"},
        {"baseInfo.SettlementItem.view", "مشاهده آیتم تسویه"},
        {"baseInfo.SettlementCause.create", "ایجاد علت تسویه حساب"},
        {"baseInfo.SettlementCause.delete", "حذف علت تسویه حساب"},
        {"baseInfo.SettlementCause.update", "بروزرسانی علت تسویه حساب"},
        {"baseInfo.SettlementCause.view", "مشاهده علت تسویه حساب"},
        {"baseInfo.Rank.create", "ایجاد رده"},
        {"baseInfo.Rank.delete", "حذف رده"},
        {"baseInfo.Rank.update", "بروزرسانی رده"},
        {"baseInfo.Rank.view", "مشاهده رده"},
        {"baseInfo.PositionManagementLevel.create", "ایجاد سطح مدیریت پست"},
        {"baseInfo.PositionManagementLevel.delete", "حذف سطح مدیریت پست"},
        {"baseInfo.PositionManagementLevel.update", "بروزرسانی سطح مدیریت پست"},
        {"baseInfo.PositionManagementLevel.view", "مشاهده سطح مدیریت پست"},
        {"baseInfo.PositionState.create", "ایجاد حالت پست"},
        {"baseInfo.PositionState.delete", "حذف حالت پست"},
        {"baseInfo.PositionState.update", "بروزرسانی حالت پست"},
        {"baseInfo.PositionState.view", "مشاهده حالت پست"},
        {"baseInfo.SettlementStatus.create", "ایجاد وضعیت تسویه حساب"},
        {"baseInfo.SettlementStatus.delete", "حذف وضعیت تسویه حساب"},
        {"baseInfo.SettlementStatus.update", "بروزرسانی وضعیت تسویه حساب"},
        {"baseInfo.SettlementStatus.view", "مشاهده وضعیت تسویه حساب"},
        {"baseInfo.SettlementDocumentAttachmentType.create", "ایجاد نوع پیوست سند تسویه حساب"},
        {"baseInfo.SettlementDocumentAttachmentType.delete", "حذف نوع پیوست سند تسویه حساب"},
        {"baseInfo.SettlementDocumentAttachmentType.update", "بروزرسانی نوع پیوست سند تسویه حساب"},
        {"baseInfo.SettlementDocumentAttachmentType.view", "مشاهده نوع پیوست سند تسویه حساب"},
        {"baseInfo.ReportMapColumn.create", "ایجاد ستون نقشه گزارش"},
        {"baseInfo.ReportMapColumn.delete", "حذف ستون نقشه گزارش"},
        {"baseInfo.ReportMapColumn.update", "بروزرسانی ستون نقشه گزارش"},
        {"baseInfo.ReportMapColumn.view", "مشاهده ستون نقشه گزارش"},
        {"baseInfo.FormulaUsageLocation.create", "ایجاد محل استفاده فرمول"},
        {"baseInfo.FormulaUsageLocation.delete", "حذف محل استفاده فرمول"},
        {"baseInfo.FormulaUsageLocation.update", "بروزرسانی محل استفاده فرمول"},
        {"baseInfo.FormulaUsageLocation.view", "مشاهده محل استفاده فرمول"},
        {"baseInfo.TaxOccupation.create", "ایجاد شغل مالیاتی"},
        {"baseInfo.TaxOccupation.delete", "حذف شغل مالیاتی"},
        {"baseInfo.TaxOccupation.update", "بروزرسانی شغل مالیاتی"},
        {"baseInfo.TaxOccupation.view", "مشاهده شغل مالیاتی"},
        {"baseInfo.Import.create", "آپلود و نهایی‌سازی Import اکسل"},
        {"baseInfo.Import.view", "مشاهده پروفایل و پیش‌نمایش Import"},
        {"baseInfo.ImportProfile.create", "ایجاد پروفایل Import"},
        {"baseInfo.ImportProfile.update", "بروزرسانی پروفایل Import"},
        {"baseInfo.ImportProfile.delete", "حذف پروفایل Import"},
        {"baseInfo.ImportProfile.view", "مشاهده پروفایل Import"},
        {"baseInfo.ImportProfileField.create", "ایجاد ستون پروفایل Import"},
        {"baseInfo.ImportProfileField.update", "بروزرسانی ستون پروفایل Import"},
        {"baseInfo.ImportProfileField.delete", "حذف ستون پروفایل Import"},
        {"baseInfo.ImportProfileField.view", "مشاهده ستون پروفایل Import"},
        {"baseInfo.ImportProfileContextField.create", "ایجاد فیلد Context پروفایل Import"},
        {"baseInfo.ImportProfileContextField.update", "بروزرسانی فیلد Context پروفایل Import"},
        {"baseInfo.ImportProfileContextField.delete", "حذف فیلد Context پروفایل Import"},
        {"baseInfo.ImportProfileContextField.view", "مشاهده فیلد Context پروفایل Import"},
        {"baseInfo.ImportBatch.create", "نهایی‌سازی دسته Import"},
        {"baseInfo.ImportBatch.delete", "حذف دسته Import"},
        {"baseInfo.ImportBatch.view", "مشاهده دسته و ردیف‌های Import"},
        {"baseInfo.ImportBatch.download", "دانلود فایل آپلود Import"},
        {"baseInfo.ImageAttachment.create", "ایجاد پیوست تصویر"},
        {"baseInfo.ImageAttachment.delete", "حذف پیوست تصویر"},
        {"baseInfo.ImageAttachment.update", "بروزرسانی پیوست تصویر"},
        {"baseInfo.ImageAttachment.view", "مشاهده پیوست تصویر"},
        {"baseInfo.JobActivityType.create", "ایجاد نوع فعالیت شغل"},
        {"baseInfo.JobActivityType.delete", "حذف نوع فعالیت شغل"},
        {"baseInfo.JobActivityType.update", "بروزرسانی نوع فعالیت شغل"},
        {"baseInfo.JobActivityType.view", "مشاهده نوع فعالیت شغل"},
        {"baseInfo.JobLevel.create", "ایجاد سطح شغل"},
        {"baseInfo.JobLevel.delete", "حذف سطح شغل"},
        {"baseInfo.JobLevel.update", "بروزرسانی سطح شغل"},
        {"baseInfo.JobLevel.view", "مشاهده سطح شغل"},
        {"baseInfo.FundType.create", "ایجاد نوع صندوق"},
        {"baseInfo.FundType.delete", "حذف نوع صندوق"},
        {"baseInfo.FundType.update", "بروزرسانی نوع صندوق"},
        {"baseInfo.FundType.view", "مشاهده نوع صندوق"},
        {"baseInfo.SkillLevel.create", "ایجاد سطح مهارت"},
        {"baseInfo.SkillLevel.delete", "حذف سطح مهارت"},
        {"baseInfo.SkillLevel.update", "بروزرسانی سطح مهارت"},
        {"baseInfo.SkillLevel.view", "مشاهده سطح مهارت"},
        {"baseInfo.Setting.create", "ایجاد تنظیمات"},
        {"baseInfo.Setting.delete", "حذف تنظیمات"},
        {"baseInfo.Setting.update", "بروزرسانی تنظیمات"},
        {"baseInfo.Setting.view", "مشاهده تنظیمات"},
        {"baseInfo.ConfidentialityLevel.create", "ایجاد سطح محرمانگی"},
        {"baseInfo.ConfidentialityLevel.delete", "حذف سطح محرمانگی"},
        {"baseInfo.ConfidentialityLevel.update", "بروزرسانی سطح محرمانگی"},
        {"baseInfo.ConfidentialityLevel.view", "مشاهده سطح محرمانگی"},
        {"baseInfo.StaffingRule.create", "ایجاد StaffingRule"},
        {"baseInfo.StaffingRule.delete", "حذف StaffingRule"},
        {"baseInfo.StaffingRule.update", "بروزرسانی StaffingRule"},
        {"baseInfo.StaffingRule.view", "مشاهده StaffingRule"},
        {"baseInfo.TaminInsuranceJobList.create", "ایجاد مشاغل تامین اجتماعی"},
        {"baseInfo.TaminInsuranceJobList.delete", "حذف مشاغل تامین اجتماعی"},
        {"baseInfo.TaminInsuranceJobList.update", "بروزرسانی مشاغل تامین اجتماعی"},
        {"baseInfo.TaminInsuranceJobList.view", "مشاهده مشاغل تامین اجتماعی"},
        {"baseInfo.BaseTaminInsuranceJobList.create", "ایجاد فهرست شغل های تامین اجتماعی"},
        {"baseInfo.BaseTaminInsuranceJobList.delete", "حذف فهرست شغل های تامین اجتماعی"},
        {"baseInfo.BaseTaminInsuranceJobList.update", "بروزرسانی فهرست شغل های تامین اجتماعی"},
        {"baseInfo.BaseTaminInsuranceJobList.view", "مشاهده فهرست شغل های تامین اجتماعی"},
        {"baseInfo.TempGlobalFile.create", "ایجاد فایل موقت کلی"},
        {"baseInfo.TempGlobalFile.delete", "حذف فایل موقت کلی"},
        {"baseInfo.TempGlobalFile.update", "بروزرسانی فایل موقت کلی"},
        {"baseInfo.TempGlobalFile.view", "مشاهده فایل موقت کلی"},
        {"baseInfo.University.create", "ایجاد دانشگاه"},
        {"baseInfo.University.delete", "حذف دانشگاه"},
        {"baseInfo.University.update", "بروزرسانی دانشگاه"},
        {"baseInfo.University.view", "مشاهده دانشگاه"},
        {"baseInfo.WageItem.create", "ایجاد عامل حقوقی"},
        {"baseInfo.WageItem.delete", "حذف عامل حقوقی"},
        {"baseInfo.WageItem.update", "بروزرسانی عامل حقوقی"},
        {"baseInfo.WageItem.view", "مشاهده عامل حقوقی"},
        {"baseInfo.ExcelDefinitionType.create", "ایجاد نوع تعریف اکسل"},
        {"baseInfo.ExcelDefinitionType.delete", "حذف نوع تعریف اکسل"},
        {"baseInfo.ExcelDefinitionType.update", "بروزرسانی نوع تعریف اکسل"},
        {"baseInfo.ExcelDefinitionType.view", "مشاهده نوع تعریف اکسل"},

        // User Issue Report
        {"baseInfo.UserIssueReport.create", "ایجاد اعلام خرابی/گزارش مشکل"},
        {"baseInfo.UserIssueReport.delete", "حذف اعلام خرابی/گزارش مشکل"},
        {"baseInfo.UserIssueReport.update", "بروزرسانی اعلام خرابی/گزارش مشکل"},
        {"baseInfo.UserIssueReport.view", "مشاهده اعلام خرابی/گزارش مشکل"},

        // User File Upload
        {"baseInfo.UserFileUpload.create", "ایجاد آپلود فایل کاربر"},
        {"baseInfo.UserFileUpload.delete", "حذف آپلود فایل کاربر"},
        {"baseInfo.UserFileUpload.view", "مشاهده آپلود فایل کاربر"},
        {"baseInfo.UserFileUpload.GetUploadValidationSettings", "فهرست پسوند های مجاز قابل آپلود"},

        // Feedback
        {"baseInfo.Feedback.create", "ایجاد انتقاد یا پیشنهاد"},
        {"baseInfo.Feedback.delete", "حذف انتقاد یا پیشنهاد"},
        {"baseInfo.Feedback.update", "بروزرسانی انتقاد یا پیشنهاد"},
        {"baseInfo.Feedback.view", "مشاهده انتقاد یا پیشنهاد"},

        // FAQ
        {"baseInfo.FAQ.create", "ایجاد سوال متداول"},
        {"baseInfo.FAQ.delete", "حذف سوال متداول"},
        {"baseInfo.FAQ.update", "بروزرسانی سوال متداول"},
        {"baseInfo.FAQ.view", "مشاهده سوال متداول"},
        {"baseInfo.Carousel.create", "ایجاد اسلاید داشبورد"},
        {"baseInfo.Carousel.delete", "حذف اسلاید داشبورد"},
        {"baseInfo.Carousel.update", "بروزرسانی اسلاید داشبورد"},
        {"baseInfo.Carousel.view", "مشاهده اسلاید داشبورد"},
        {"baseInfo.RequestDocumentRequirement.create", "ایجاد الزامات اسناد درخواست"},
        {"baseInfo.RequestDocumentRequirement.delete", "حذف الزامات اسناد درخواست"},
        {"baseInfo.RequestDocumentRequirement.update", "بروزرسانی الزامات اسناد درخواست"},
        {"baseInfo.RequestDocumentRequirement.view", "مشاهده الزامات اسناد درخواست"},
        {"baseInfo.EmployeeRequestStatus.create", "ایجاد وضعیت درخواست کارمند"},
        {"baseInfo.EmployeeRequestStatus.delete", "حذف وضعیت درخواست کارمند"},
        {"baseInfo.EmployeeRequestStatus.update", "بروزرسانی وضعیت درخواست کارمند"},
        {"baseInfo.EmployeeRequestStatus.view", "مشاهده وضعیت درخواست کارمند"},
        {"baseInfo.SystemGuide.create", "ایجاد راهنمای سامانه"},
        {"baseInfo.SystemGuide.delete", "حذف راهنمای سامانه"},
        {"baseInfo.SystemGuide.update", "بروزرسانی راهنمای سامانه"},
        {"baseInfo.SystemGuide.view", "مشاهده راهنمای سامانه"},

        {"baseInfo.ManagementAndStewardshipJob.create", "ایجاد مشاغل پایه و مدیریت سرپرستی"},
        {"baseInfo.ManagementAndStewardshipJob.delete", "حذف مشاغل پایه و مدیریت سرپرستی"},
        {"baseInfo.ManagementAndStewardshipJob.update", "بروز رسانی مشاغل پایه و مدیریت سرپرستی"},
        {"baseInfo.ManagementAndStewardshipJob.view", " مشاهده مشاغل پایه و مدیریت سرپرستی"},

        // Version Management
        {"baseInfo.Version.create", "ایجاد نسخه"},
        {"baseInfo.Version.delete", "حذف نسخه"},
        {"baseInfo.Version.update", "بروزرسانی نسخه"},
        {"baseInfo.Version.view", "مشاهده نسخه"},
        {"baseInfo.VersionChangeLog.create", "ایجاد تغییر نسخه"},
        {"baseInfo.VersionChangeLog.delete", "حذف تغییر نسخه"},
        {"baseInfo.VersionChangeLog.update", "بروزرسانی تغییر نسخه"},
        {"baseInfo.VersionChangeLog.view", "مشاهده تغییر نسخه"},

    };

    /// <summary>
    /// Resolves the Persian description for a controller/action permission key.
    /// Matches both short keys (e.g. Order.GetOrderYearlyLandingPageSummary) and
    /// full keys (e.g. OrderNameSpace.Order.GetOrderYearlyLandingPageSummary).
    /// </summary>
    public static string? TryResolveActionDescription(string? controller, string? action)
        => TryResolveDescription(controller, action);

    public static string? TryResolveDescription(string? controller, string? action)
    {
        if (string.IsNullOrWhiteSpace(controller) || string.IsNullOrWhiteSpace(action))
            return null;

        var shortKey = $"{controller}.{action}";
        if (CustomAccessKeyDesc.TryGetValue(shortKey, out var direct))
            return direct;

        foreach (var entry in CustomAccessKeyDesc)
        {
            if (entry.Key.EndsWith(shortKey, StringComparison.OrdinalIgnoreCase))
                return entry.Value;
        }

        return null;
    }

    /// <summary>
    /// Returns the module/group segment of a full permission key for the given action
    /// (e.g. OrderNameSpace for Order.GetOrderYearlyLandingPageSummary).
    /// </summary>
    public static string? TryResolveModuleKey(string? controller, string? action)
    {
        if (string.IsNullOrWhiteSpace(controller) || string.IsNullOrWhiteSpace(action))
            return null;

        var suffix = $"{controller}.{action}";
        foreach (var entry in CustomAccessKeyDesc)
        {
            if (!entry.Key.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
                continue;

            var parts = entry.Key.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (parts.Length >= 3)
                return parts[0];
        }

        return null;
    }
}