// <auto-generated />
using System;
using HR.Attendance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.Attendance.Infrastructure.Migrations
{
    [DbContext(typeof(AttendanceContext))]
    [Migration("20260710085423_AddOUIndex")]
    partial class AddOUIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR.Attendance.Core.Entities.AttendanceCalendar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasComment("تاریخ");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<long?>("HolidayId")
                        .HasColumnType("bigint")
                        .HasComment("تعطیلات مرتبط");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("bit")
                        .HasComment("تعطیل");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("WeekDay")
                        .HasColumnType("int")
                        .HasComment("روز هفته (مطابق DayOfWeek)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("HolidayId");

                    b.ToTable("Attendance_Calendar", "Attendance");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.AttendanceDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AttendanceLocationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint")
                        .HasComment("base table value Id : 40300 (برند دستگاه)");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("کد دستگاه");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DeviceIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasComment("آدرس IP دستگاه");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("نوع دستگاه");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime2")
                        .HasComment("آخرین تاریخ همگام‌سازی");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("مدل دستگاه");

                    b.Property<long>("OrganisationChartId")
                        .HasColumnType("bigint");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasComment("پورت");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("شماره سریال");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint")
                        .HasComment("base table value Id : 40299 (وضعیت دستگاه)");

                    b.Property<int>("SyncInterval")
                        .HasColumnType("int")
                        .HasComment("فاصله همگام‌سازی (دقیقه)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("منطقه زمانی");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceLocationId");

                    b.HasIndex("OrganisationChartId");

                    b.ToTable("Attendance_Device", "Attendance");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.AttendanceLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("آدرس");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("کد محل حضور");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasComment("عرض جغرافیایی");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasComment("طول جغرافیایی");

                    b.Property<long>("OrganisationChartId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Radius")
                        .HasColumnType("decimal(10,2)")
                        .HasComment("شعاع مجاز (متر)");

                    b.Property<long?>("RelatedOrganisationChartId")
                        .HasColumnType("bigint")
                        .HasComment("واحد سازمانی مرتبط");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationChartId");

                    b.HasIndex("RelatedOrganisationChartId");

                    b.ToTable("Attendance_Location", "Attendance");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.EmployeeSpecific.EmployeeAttendanceDailyResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AbsentSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه غیبت");

                    b.Property<long>("AttendanceCalendarId")
                        .HasColumnType("bigint");

                    b.Property<int>("BreakSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه استراحت");

                    b.Property<DateTime?>("CalculateDate")
                        .HasColumnType("datetime")
                        .HasComment("تاریخ محاسبه");

                    b.Property<int>("CalculationVersion")
                        .HasColumnType("int")
                        .HasComment("نسخه محاسبه");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DelaySeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه تأخیر");

                    b.Property<int>("EarlyLeaveSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه تعجیل در خروج");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FirstIn")
                        .HasColumnType("datetime")
                        .HasComment("اولین ورود");

                    b.Property<int>("HolidayWorkSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه کار در تعطیل");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastOut")
                        .HasColumnType("datetime")
                        .HasComment("آخرین خروج");

                    b.Property<int>("LeaveSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه مرخصی");

                    b.Property<int>("MissionSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه مأموریت");

                    b.Property<int>("NightWorkSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه کار شب");

                    b.Property<long>("OrganisationChartId")
                        .HasColumnType("bigint");

                    b.Property<int>("OvertimeSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه اضافه‌کار");

                    b.Property<int>("PaidBreakSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه استراحت با حقوق");

                    b.Property<int>("RequiredSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه مورد نیاز");

                    b.Property<long>("ShiftId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("UnpaidBreakSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه استراحت بدون حقوق");

                    b.Property<int>("WorkedSeconds")
                        .HasColumnType("int")
                        .HasComment("ثانیه کارکرد");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceCalendarId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("OrganisationChartId", "EmployeeId", "AttendanceCalendarId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Employee_Attendance_Daily_Result", "Attendance");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.EmployeeSpecific.EmployeeAttendanceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AttendanceDeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DeviceUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("شناسه کاربر در دستگاه");

                    b.Property<string>("Direction")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("جهت تردد");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LogDateTime")
                        .HasColumnType("datetime2")
                        .HasComment("زمان ثبت در دستگاه");

                    b.Property<bool?>("Mask")
                        .HasColumnType("bit")
                        .HasComment("ماسک");

                    b.Property<string>("RawData")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("داده خام دستگاه");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasColumnType("datetime2")
                        .HasComment("زمان دریافت در سامانه");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("وضعیت پردازش");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5,2)")
                        .HasComment("دمای اندازه‌گیری شده");

                    b.Property<string>("VerifyMode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("نوع احراز هویت");

                    b.Property<string>("WorkCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("کد کار");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceDeviceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Employee_Attendance_Log", "Attendance");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.EmployeeSpecific.EmployeeShiftAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("توضیحات");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<long>("OrganisationChartId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShiftId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganisationChartId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Attendance_Employee_Shift_Assignment", "Attendance");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.Shift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("کد شیفت");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasComment("رنگ نمایشی (hex)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("CrossDay")
                        .HasColumnType("bit")
                        .HasComment("عبور از نیمه‌شب");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasComment("ساعت پایان کار");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("فعال");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFlexible")
                        .HasColumnType("bit")
                        .HasComment("شیفت منعطف");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan?>("MaxInTime")
                        .HasColumnType("time")
                        .HasComment("حداکثر زمان ورود");

                    b.Property<TimeSpan?>("MaxOutTime")
                        .HasColumnType("time")
                        .HasComment("حداکثر زمان خروج");

                    b.Property<TimeSpan?>("MinInTime")
                        .HasColumnType("time")
                        .HasComment("حداقل زمان ورود");

                    b.Property<TimeSpan?>("MinOutTime")
                        .HasColumnType("time")
                        .HasComment("حداقل زمان خروج");

                    b.Property<bool>("NightShift")
                        .HasColumnType("bit")
                        .HasComment("شیفت شب");

                    b.Property<long>("OrganisationChartId")
                        .HasColumnType("bigint");

                    b.Property<int>("RequiredWorkSeconds")
                        .HasColumnType("int")
                        .HasComment("مدت کار مورد نیاز (ثانیه)");

                    b.Property<TimeSpan?>("RestEnd")
                        .HasColumnType("time")
                        .HasComment("پایان استراحت");

                    b.Property<TimeSpan?>("RestStart")
                        .HasColumnType("time")
                        .HasComment("شروع استراحت");

                    b.Property<int?>("RoundType")
                        .HasColumnType("int")
                        .HasComment("نوع گرد کردن زمان");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasComment("ساعت شروع کار");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationChartId");

                    b.ToTable("Attendance_Shift", "Attendance");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.AttendanceHoliday", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<long>("PlaceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("AttendanceHoliday", "bas", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.BaseTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MetaData")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Base_Table", "bas");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.BaseTableValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseTableId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BaseTableId");

                    b.ToTable("Base_Table_Value", "bas");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.ConfidentialityLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ConfidentialityLevel", "bas");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.ManagementAndStewardshipJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Management_And_StewardshipJob", "bas");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.OrganizationType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Organization_Type", "bas");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.Places", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<long?>("ParentPlaceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlaceTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ParentPlaceId");

                    b.HasIndex("PlaceTypeId");

                    b.ToTable("Places", "bas");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.SkillLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Skill_Level", "bas");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.TaminInsuranceJobList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Tamin_Insurance_JobList", "bas");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.TaxExemptionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Tax_Exemption_Type", "bas");
                });

            modelBuilder.Entity("HR.Employee.Core.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountingSystemEmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActiveName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("BaseOrganisationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<long?>("BirthPlaceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BloodGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CitizenshipId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompeleteInsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ConfidentialityLevelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Descriptions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FatherName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("GenderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("HeadquartersOrRowTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IdentityNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("Imperfective")
                        .HasColumnType("int");

                    b.Property<string>("InOutCard")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCashBenefits")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHekmat")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerify")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsWelfareBenefits")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWomenHead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<long?>("IssuePlaceId")
                        .HasColumnType("bigint");

                    b.Property<int?>("IssueSerialChar")
                        .HasColumnType("int");

                    b.Property<string>("IssueSerialOrder")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IssueSerialString")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastWrongAttemptDatetime")
                        .HasColumnType("datetime");

                    b.Property<long?>("LifeAccidentInsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("LostIssueSerialString")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("ManagementAndStewardshipJobId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaritalStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("MartyrChildTrackingCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("MartyrRelationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MazhabId")
                        .HasColumnType("bigint");

                    b.Property<string>("NationalNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("NationalityId")
                        .HasColumnType("bigint");

                    b.Property<string>("PassportNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("PersonelCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("PrivateJobStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("ReligeonId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SectId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ServicePlaceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SkillLevelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartWorkDate")
                        .HasColumnType("date");

                    b.Property<int>("SubsystemId")
                        .HasColumnType("int");

                    b.Property<long?>("TaminInsuranceJobListId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TaxExemptionTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<long?>("UseCompeleteInsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UseLifeAccidentInsuranceTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VehicleStatusId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("salt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseOrganisationId");

                    b.HasIndex("BirthPlaceId");

                    b.HasIndex("BloodGroupId");

                    b.HasIndex("CitizenshipId");

                    b.HasIndex("ConfidentialityLevelId");

                    b.HasIndex("GenderId");

                    b.HasIndex("HeadquartersOrRowTypeId");

                    b.HasIndex("IssuePlaceId");

                    b.HasIndex("ManagementAndStewardshipJobId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("MartyrRelationId");

                    b.HasIndex("MazhabId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("ReligeonId");

                    b.HasIndex("ServicePlaceId");

                    b.HasIndex("SkillLevelId");

                    b.HasIndex("TaminInsuranceJobListId");

                    b.HasIndex("TaxExemptionTypeId");

                    b.ToTable("Employee", "emp");
                });

            modelBuilder.Entity("HR.Organisation.Core.Entities.OrganisationChart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCostCenter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsIndependentOrg")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOrg")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPayLocation")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRegister")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LetterCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("OrgTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizationTypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentOrganisationChartId")
                        .HasColumnType("bigint");

                    b.Property<string>("Rank")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SystemCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("TaxNodeStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationTypeId");

                    b.HasIndex("ParentOrganisationChartId");

                    b.ToTable("Organisation_Chart", "Org");
                });

            modelBuilder.Entity("HR.SharedKernel.Data.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.AttendanceCalendar", b =>
                {
                    b.HasOne("HR.BaseInfo.Core.Entities.AttendanceHoliday", "Holiday")
                        .WithMany()
                        .HasForeignKey("HolidayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Holiday");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.AttendanceDevice", b =>
                {
                    b.HasOne("HR.Attendance.Core.Entities.AttendanceLocation", "AttendanceLocation")
                        .WithMany()
                        .HasForeignKey("AttendanceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "OrganisationChart")
                        .WithMany()
                        .HasForeignKey("OrganisationChartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceLocation");

                    b.Navigation("OrganisationChart");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.AttendanceLocation", b =>
                {
                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "OrganisationChart")
                        .WithMany()
                        .HasForeignKey("OrganisationChartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "RelatedOrganisationChart")
                        .WithMany()
                        .HasForeignKey("RelatedOrganisationChartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrganisationChart");

                    b.Navigation("RelatedOrganisationChart");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.EmployeeSpecific.EmployeeAttendanceDailyResult", b =>
                {
                    b.HasOne("HR.Attendance.Core.Entities.AttendanceCalendar", "AttendanceCalendar")
                        .WithMany()
                        .HasForeignKey("AttendanceCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Employee.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "OrganisationChart")
                        .WithMany()
                        .HasForeignKey("OrganisationChartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Attendance.Core.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceCalendar");

                    b.Navigation("Employee");

                    b.Navigation("OrganisationChart");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.EmployeeSpecific.EmployeeAttendanceLog", b =>
                {
                    b.HasOne("HR.Attendance.Core.Entities.AttendanceDevice", "AttendanceDevice")
                        .WithMany()
                        .HasForeignKey("AttendanceDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Employee.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceDevice");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.EmployeeSpecific.EmployeeShiftAssignment", b =>
                {
                    b.HasOne("HR.Employee.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "OrganisationChart")
                        .WithMany()
                        .HasForeignKey("OrganisationChartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Attendance.Core.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("OrganisationChart");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HR.Attendance.Core.Entities.Shift", b =>
                {
                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "OrganisationChart")
                        .WithMany()
                        .HasForeignKey("OrganisationChartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganisationChart");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.AttendanceHoliday", b =>
                {
                    b.HasOne("HR.BaseInfo.Core.Entities.Places", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.BaseTableValue", b =>
                {
                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTable", "BaseTable")
                        .WithMany("BaseTableValues")
                        .HasForeignKey("BaseTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseTable");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.Places", b =>
                {
                    b.HasOne("HR.BaseInfo.Core.Entities.Places", "ParentPlace")
                        .WithMany()
                        .HasForeignKey("ParentPlaceId");

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "PlaceType")
                        .WithMany()
                        .HasForeignKey("PlaceTypeId");

                    b.Navigation("ParentPlace");

                    b.Navigation("PlaceType");
                });

            modelBuilder.Entity("HR.Employee.Core.Entities.Employee", b =>
                {
                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "BaseOrganisation")
                        .WithMany()
                        .HasForeignKey("BaseOrganisationId");

                    b.HasOne("HR.BaseInfo.Core.Entities.Places", "BirthPlace")
                        .WithMany()
                        .HasForeignKey("BirthPlaceId");

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "BloodGroup")
                        .WithMany()
                        .HasForeignKey("BloodGroupId");

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "Citizenship")
                        .WithMany()
                        .HasForeignKey("CitizenshipId");

                    b.HasOne("HR.BaseInfo.Core.Entities.ConfidentialityLevel", "ConfidentialityLevel")
                        .WithMany()
                        .HasForeignKey("ConfidentialityLevelId");

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "HeadquartersOrRowType")
                        .WithMany()
                        .HasForeignKey("HeadquartersOrRowTypeId");

                    b.HasOne("HR.BaseInfo.Core.Entities.Places", "IssuePlace")
                        .WithMany()
                        .HasForeignKey("IssuePlaceId");

                    b.HasOne("HR.BaseInfo.Core.Entities.ManagementAndStewardshipJob", "ManagementAndStewardshipJob")
                        .WithMany()
                        .HasForeignKey("ManagementAndStewardshipJobId");

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusId");

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "MartyrRelation")
                        .WithMany()
                        .HasForeignKey("MartyrRelationId");

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "Mazhab")
                        .WithMany()
                        .HasForeignKey("MazhabId");

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("HR.BaseInfo.Core.Entities.BaseTableValue", "Religeon")
                        .WithMany()
                        .HasForeignKey("ReligeonId");

                    b.HasOne("HR.BaseInfo.Core.Entities.Places", "ServicePlace")
                        .WithMany()
                        .HasForeignKey("ServicePlaceId");

                    b.HasOne("HR.BaseInfo.Core.Entities.SkillLevel", "SkillLevel")
                        .WithMany()
                        .HasForeignKey("SkillLevelId");

                    b.HasOne("HR.BaseInfo.Core.Entities.TaminInsuranceJobList", "TaminInsuranceJobList")
                        .WithMany()
                        .HasForeignKey("TaminInsuranceJobListId");

                    b.HasOne("HR.BaseInfo.Core.Entities.TaxExemptionType", "TaxExemptionType")
                        .WithMany()
                        .HasForeignKey("TaxExemptionTypeId");

                    b.Navigation("BaseOrganisation");

                    b.Navigation("BirthPlace");

                    b.Navigation("BloodGroup");

                    b.Navigation("Citizenship");

                    b.Navigation("ConfidentialityLevel");

                    b.Navigation("Gender");

                    b.Navigation("HeadquartersOrRowType");

                    b.Navigation("IssuePlace");

                    b.Navigation("ManagementAndStewardshipJob");

                    b.Navigation("MaritalStatus");

                    b.Navigation("MartyrRelation");

                    b.Navigation("Mazhab");

                    b.Navigation("Nationality");

                    b.Navigation("Religeon");

                    b.Navigation("ServicePlace");

                    b.Navigation("SkillLevel");

                    b.Navigation("TaminInsuranceJobList");

                    b.Navigation("TaxExemptionType");
                });

            modelBuilder.Entity("HR.Organisation.Core.Entities.OrganisationChart", b =>
                {
                    b.HasOne("HR.BaseInfo.Core.Entities.OrganizationType", "OrganizationType")
                        .WithMany()
                        .HasForeignKey("OrganizationTypeId");

                    b.HasOne("HR.Organisation.Core.Entities.OrganisationChart", "ParentOrganisationChart")
                        .WithMany()
                        .HasForeignKey("ParentOrganisationChartId");

                    b.Navigation("OrganizationType");

                    b.Navigation("ParentOrganisationChart");
                });

            modelBuilder.Entity("HR.BaseInfo.Core.Entities.BaseTable", b =>
                {
                    b.Navigation("BaseTableValues");
                });
#pragma warning restore 612, 618
        }
    }
}
